In [150]:
import numpy as np 
import pandas as pd 
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

In [151]:
cbb = pd.read_csv('/Users/visheshgupta/Desktop/Final_Project_DE/archive/cbb.csv')

In [152]:
cbb.columns

Index(['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'POSTSEASON', 'SEED', 'YEAR'],
      dtype='object')

In [153]:
cbb24 = pd.read_csv('/Users/visheshgupta/Desktop/Final_Project_DE/archive/cbb24.csv')

In [154]:
cbb24.columns

Index(['RK', 'TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG%',
       'EFGD%', 'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D',
       '3P_O', '3P_D', 'ADJ_T', 'WAB', 'SEED'],
      dtype='object')

In [155]:
cbb24['EFG_O'] = cbb24['EFG%']
cbb24['EFG_D'] = cbb24['EFGD%']
cbb24 = cbb24[['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'SEED']]

In [156]:
cbb24

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,SEED
0,Houston,B12,34,30,119.2,85.5,0.9785,49.7,44.0,13.7,...,30.2,29.9,39.0,48.4,43.4,34.7,30.0,63.3,10.6,1.0
1,Connecticut,BE,34,31,127.1,93.6,0.9712,57.1,45.1,14.9,...,26.8,33.3,32.5,58.5,43.7,36.7,31.9,64.6,11.3,1.0
2,Purdue,B10,33,29,126.2,94.7,0.9644,56.0,47.7,16.5,...,24.7,42.8,23.0,53.2,48.1,40.8,31.4,67.6,11.0,1.0
3,Iowa St.,B12,34,27,113.6,86.5,0.9583,51.9,47.1,15.7,...,29.4,36.1,35.2,51.7,46.9,34.9,31.5,67.6,6.9,2.0
4,Auburn,SEC,34,27,120.7,92.1,0.9573,54.1,43.4,14.9,...,30.3,38.2,41.0,54.9,42.8,35.2,29.8,69.8,5.5,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,Stonehill,NEC,30,4,90.3,114.2,0.0629,46.7,52.7,19.5,...,31.0,22.6,29.4,47.9,51.7,30.1,35.9,68.1,-22.0,NaN
358,St. Francis PA,NEC,28,8,93.1,118.1,0.0608,47.2,53.0,21.2,...,31.3,32.6,35.4,45.7,52.9,33.2,35.4,65.4,-18.6,NaN
359,IUPUI,Horz,29,6,92.1,116.9,0.0607,46.5,58.2,21.3,...,35.5,33.2,33.4,49.5,59.0,24.7,38.0,67.3,-21.6,NaN
360,Coppin St.,MEAC,29,2,85.1,111.1,0.0445,42.1,51.3,22.9,...,38.6,31.1,38.3,41.9,51.0,28.3,34.5,66.3,-22.9,NaN
361,Mississippi Valley St.,SWAC,31,1,85.4,116.2,0.0283,42.5,55.6,24.0,...,35.7,33.0,41.6,41.9,55.6,29.2,37.0,64.5,-22.7,NaN

In [157]:
cbb

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,...,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,...,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,...,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,...,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,...,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3518,Toledo,MAC,34,27,119.9,109.6,0.7369,56.3,52.9,13.6,...,27.5,54.6,52.1,39.7,36.1,69.5,-1.2,NaN,NaN,2023
3519,Liberty,ASun,33,27,111.4,97.3,0.8246,55.5,49.3,16.0,...,27.8,56.4,48.6,36.4,33.6,64.4,-2.0,NaN,NaN,2023
3520,Utah Valley,WAC,34,28,107.1,94.6,0.8065,51.7,44.0,19.3,...,28.7,52.5,42.8,33.4,31.1,69.8,-0.3,NaN,NaN,2023
3521,UAB,CUSA,38,29,112.4,97.0,0.8453,50.3,47.3,17.3,...,28.9,48.8,47.2,35.6,31.6,70.7,-0.5,NaN,NaN,2023
3522,North Texas,CUSA,36,31,110.0,93.8,0.8622,51.2,44.5,19.8,...,40.2,49.6,44.2,35.7,30.1,58.7,1.1,NaN,NaN,2023

In [158]:
cbb.to_csv('train_data.csv', index=False)

In [159]:
cbb24.to_csv('test_data.csv', index=False)

In [160]:
#dummy data:

In [161]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.barttorvik.com/"
response = requests.get(url)

# Parse the HTML
soup = BeautifulSoup(response.text, "html.parser")

# Inspect the page structure and find the table or relevant data
# Example: Extracting table data
table = soup.find("table")
rows = table.find_all("tr")

data = []
for row in rows:
    cols = row.find_all("td")
    cols = [ele.text.strip() for ele in cols]
    data.append(cols)

# Convert to DataFrame and save as CSV
df = pd.DataFrame(data)
df = df.dropna(how="all").reset_index(drop=True)

df.columns = ['RK', 'TEAM', 'CONF', 'G', 'REC', 'ADJOE', 'ADJDE', 'BARTHAG', "EFG_O", "EFG_D", 'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', "2P_O", "2P_D", "3P_O", "3P_D", '3PR', '3PRD', 'ADJ_T', 'WAB']
df = df[[
    "TEAM", "CONF", "G", "ADJOE", "ADJDE", "BARTHAG", 
    "EFG_O", "EFG_D", "TOR", "TORD", "ORB", "DRB", "FTR", "FTRD", 
    "2P_O", "2P_D", "3P_O", "3P_D", "ADJ_T", "WAB"
]]
df.to_csv("current_cbb_live_data.csv", index=False)

In [162]:
df.columns

Index(['TEAM', 'CONF', 'G', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB'],
      dtype='object')

In [163]:

cbb.columns

Index(['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'POSTSEASON', 'SEED', 'YEAR'],
      dtype='object')

In [164]:
cbb24.columns

Index(['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'SEED'],
      dtype='object')

In [165]:
len(cbb.columns)

24

In [166]:
len(cbb24.columns)

22

In [167]:
'''   
# columns that we are missing in our scrapped date:
1. W : no of  games a team won
2. POST SEASON: What position they finished. This is what we are predciting so we are good
3. Seed: We cannot know this information 
4. Year: This is Trivial 
'''

'   \n# columns that we are missing in our scrapped date:\n1. W : no of  games a team won\n2. POST SEASON: What position they finished. This is what we are predciting so we are good\n3. Seed: We cannot know this information \n4. Year: This is Trivial \n'

In [168]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

cbb_model = cbb[cbb['SEED'].notnull()]

cbb_model['SEED'] = cbb_model['SEED'].astype(int)

features = [
    'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D', 'TOR', 'TORD', 'ORB',
    'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O', '3P_D', 'ADJ_T', 'WAB'
]
X = cbb_model[features]
y = cbb_model['SEED']

cbb24_seedless = cbb24[features]  

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
cbb24_scaled = scaler.transform(cbb24_seedless)

models = {
    'Linear Regression': LinearRegression(),
    'Random Forest': RandomForestRegressor(random_state=42, n_estimators=100),
    'XGBoost': XGBRegressor(random_state=42)
}

results = {}
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_pred_rounded = np.round(y_pred).clip(1, 16)  # Clip predictions to valid seed range
    mae = mean_absolute_error(y_test, y_pred_rounded)
    results[model_name] = mae

# Predict seeds for cbb24 using the best-performing model
best_model_name = max(results, key=results.get)
best_model = models[best_model_name]
cbb24_predictions = best_model.predict(cbb24_scaled)
cbb24['predicted_seed_score'] = cbb24_predictions  # Store raw predictions for ranking

# Rank teams based on predicted seed scores
cbb24['rank'] = cbb24['predicted_seed_score'].rank(method='min', ascending=True)

# Assign seeds to top 68 teams
cbb24['predicted_seed'] = np.nan  # Initialize with NaN
top_68 = cbb24.nsmallest(68, 'predicted_seed_score')  # Select top 68 teams

# Create seed values for 68 teams
seed_values = []
for seed in range(1, 17):
    if seed == 11 or seed == 16:
        seed_values.extend([seed] * 6)  # 6 teams for seeds 11 and 16
    else:
        seed_values.extend([seed] * 4)  # 4 teams for other seeds

# Assign seeds to the top 68 teams
top_68['predicted_seed'] = seed_values

# Update the main DataFrame with the seeded teams
cbb24.update(top_68) 
cbb24 = cbb24.sort_values(by='predicted_seed')

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_81611/150274500.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb_model['SEED'] = cbb_model['SEED'].astype(int)

In [169]:
results

{'Linear Regression': 1.0514705882352942,
 'Random Forest': 1.0808823529411764,
 'XGBoost': 1.1544117647058822}

In [170]:
cbb['POSTSEASON'].unique()

array(['2ND', 'Champions', 'E8', 'F4', nan, 'R32', 'R64', 'R68', 'S16'],
      dtype=object)

In [171]:
# Preprocess the POSTSEASON column in cbb
cbb = cbb[cbb['POSTSEASON'].notnull()]  # Filter rows with POSTSEASON values
label_encoder = LabelEncoder()
cbb['POSTSEASON_LABEL'] = label_encoder.fit_transform(cbb['POSTSEASON'])  # Encode POSTSEASON

# Select features for modeling
postseason_features = [
    'predicted_seed', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D', 'TOR',
    'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O', '3P_D',
    'ADJ_T', 'WAB'
]

# Replace SEED with predicted_seed for cbb
cbb['predicted_seed'] = cbb['SEED']  # Use actual SEED for training

# Define X and y for training
X_postseason = cbb[postseason_features]
y_postseason = cbb['POSTSEASON_LABEL']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_postseason, y_postseason, test_size=0.2, random_state=42
)

# Train a Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=42, n_estimators=100)
rf_classifier.fit(X_train, y_train)

# Evaluate on test data
y_pred = rf_classifier.predict(X_test)
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

# Apply the model to cbb24 data
cbb24_seeded = cbb24.dropna(subset=['predicted_seed'])

X_cbb24 = cbb24_seeded[postseason_features]
postseason_probs = rf_classifier.predict_proba(X_cbb24)

# Define the number of teams per label
label_counts = {
    'Champion': 1,
    'Runner-Up': 1,
    'Final Four': 2,
    'Elite Eight': 4,
    'Sweet Sixteen': 8,
    'Round of 32': 16,
    'Round of 64': 32
}

# Assign labels systematically
num_labels = len(label_counts)
assigned_labels = np.full(len(cbb24_seeded), num_labels - 1)  # Default to lowest label
remaining_teams = list(range(len(cbb24_seeded)))

# Loop through each label, starting with the highest rank (Champion)
for label_idx, (label, count) in enumerate(label_counts.items()):
    # Select top teams based on probabilities for the current label
    if len(remaining_teams) == 0:
        break
    label_probs = postseason_probs[remaining_teams, label_idx]
    top_indices = np.argsort(label_probs)[-count:]  # Get indices of top `count` teams
    top_team_indices = [remaining_teams[i] for i in top_indices]  # Map back to original indices
    for i in top_team_indices:
        assigned_labels[i] = label_idx
    remaining_teams = [team for team in remaining_teams if team not in top_team_indices]  # Exclude assigned teams

# Map assigned labels back to POSTSEASON names
cbb24_seeded['predicted_postseason_label'] = assigned_labels

              precision    recall  f1-score   support

         2ND       0.00      0.00      0.00         2
   Champions       0.00      0.00      0.00         1
          E8       0.00      0.00      0.00         8
          F4       0.00      0.00      0.00         7
         R32       0.52      0.28      0.36        40
         R64       0.65      0.77      0.70        66
         R68       0.00      0.00      0.00         5
         S16       0.15      0.71      0.25         7

    accuracy                           0.49       136
   macro avg       0.17      0.22      0.16       136
weighted avg       0.48      0.49      0.46       136

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_81611/4232653574.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb['POSTSEASON_LABEL'] = label_encoder.fit_transform(cbb['POSTSEASON'])  # Encode POSTSEASON
/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_81611/4232653574.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb['predicted_seed'] = cbb['SEED']  # Use actual SEED for training
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_81611/4232653574.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb24_seeded['predicted_postseason_label'] = assigned_labels

In [172]:
postseason_mapping = {
    0: 'Winner',
    1: 'Runner-Up',
    2: 'Final Four',
    3: 'Elite Eight',
    4: 'Sweet Sixteen',
    5: 'Round of 32',
    6: 'Round of 64'
}

# Map the numerical labels to their descriptions
cbb24_seeded['predicted_postseason_description'] = cbb24_seeded['predicted_postseason_label'].map(postseason_mapping)

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_81611/3013661406.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb24_seeded['predicted_postseason_description'] = cbb24_seeded['predicted_postseason_label'].map(postseason_mapping)

In [173]:
cbb24_seeded.sort_values('predicted_postseason_label').head(16)

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,3P_O,3P_D,ADJ_T,WAB,SEED,predicted_seed_score,rank,predicted_seed,predicted_postseason_label,predicted_postseason_description
1,Connecticut,BE,34,31,127.1,93.6,0.9712,57.1,45.1,14.9,...,36.7,31.9,64.6,11.30,1.0,1.219785,1.0,1.0,0,Winner
2,Purdue,B10,33,29,126.2,94.7,0.9644,56.0,47.7,16.5,...,40.8,31.4,67.6,11.00,1.0,1.651423,2.0,1.0,1,Runner-Up
3,Iowa St.,B12,34,27,113.6,86.5,0.9583,51.9,47.1,15.7,...,34.9,31.5,67.6,6.90,2.0,1.966927,4.0,1.0,2,Final Four
4,Auburn,SEC,34,27,120.7,92.1,0.9573,54.1,43.4,14.9,...,35.2,29.8,69.8,5.50,4.0,4.541897,10.0,3.0,2,Final Four
0,Houston,B12,34,30,119.2,85.5,0.9785,49.7,44.0,13.7,...,34.7,30.0,63.3,10.60,1.0,1.754744,3.0,1.0,3,Elite Eight
7,Marquette,BE,34,25,118.9,94.6,0.9328,55.1,49.7,14.3,...,35.8,33.6,69.1,6.50,2.0,3.288688,6.0,2.0,3,Elite Eight
11,Illinois,B10,34,26,125.3,101.1,0.9221,53.8,48.0,15.1,...,34.9,34.3,69.9,6.00,3.0,3.945184,8.0,2.0,3,Elite Eight
39,Dayton,A10,31,24,117.4,100.7,0.8547,56.6,47.9,15.8,...,40.2,31.7,64.0,2.60,7.0,8.275740,27.0,7.0,3,Elite Eight
35,Ohio St.,B10,33,20,115.5,98.4,0.8636,51.2,48.2,15.6,...,34.3,34.7,65.4,-0.23,NaN,9.009435,31.0,8.0,4,Sweet Sixteen
46,South Carolina,SEC,33,26,114.4,98.9,0.8420,50.8,48.0,15.5,...,33.5,33.6,63.0,4.70,6.0,7.993735,26.0,7.0,4,Sweet Sixteen
28,San Diego St.,MWC,32,24,111.5,93.9,0.8789,49.8,47.2,16.0,...,31.3,30.5,66.1,2.60,5.0,7.298680,25.0,7.0,4,Sweet Sixteen
25,New Mexico,MWC,34,26,114.8,95.5,0.8927,51.0,48.0,13.9,...,33.4,30.6,72.8,1.70,11.0,9.050807,33.0,9.0,4,Sweet Sixteen
22,Michigan St.,B10,33,19,112.7,93.3,0.8983,51.5,48.0,14.7,...,35.9,32.8,65.3,0.21,9.0,9.551414,39.0,10.0,4,Sweet Sixteen
19,Texas,B12,32,20,119.0,98.3,0.9006,53.7,49.0,16.6,...,36.1,34.8,67.2,1.20,7.0,8.871719,30.0,8.0,4,Sweet Sixteen
20,St. John's,BE,33,20,119.1,98.3,0.9005,50.9,49.5,15.7,...,34.1,35.0,69.2,0.32,NaN,9.025539,32.0,8.0,4,Sweet Sixteen
27,Texas Tech,B12,33,23,117.5,98.4,0.8846,52.8,49.1,16.5,...,36.5,32.1,66.4,3.40,6.0,5.909659,16.0,4.0,4,Sweet Sixteen

In [174]:
''' 
now to the above we need to do the following:
    1. We need to get the seeds for the current data 
    2. We need to then run to see the final finishes 
'''

' \nnow to the above we need to do the following:\n    1. We need to get the seeds for the current data \n    2. We need to then run to see the final finishes \n'

In [175]:
cbb25 = pd.read_csv('/Users/visheshgupta/Desktop/Final_Project_DE/current_cbb_live_data.csv')

In [176]:
cbb25_seedless = cbb25[features]  
cbb25_scaled = scaler.transform(cbb25_seedless)
cbb25_predictions = best_model.predict(cbb25_scaled)
cbb25['predicted_seed_score'] = cbb25_predictions  # Store raw predictions for ranking

# Rank teams based on predicted seed scores
cbb25['rank'] = cbb25['predicted_seed_score'].rank(method='min', ascending=True)

# Assign seeds to top 68 teams
cbb25['predicted_seed'] = np.nan  # Initialize with NaN
top_68_25 = cbb25.nsmallest(68, 'predicted_seed_score')  # Select top 68 teams

# Create seed values for 68 teams
seed_values = []
for seed in range(1, 17):
    if seed == 11 or seed == 16:
        seed_values.extend([seed] * 6)  # 6 teams for seeds 11 and 16
    else:
        seed_values.extend([seed] * 4)  # 4 teams for other seeds

# Assign seeds to the top 68 teams
top_68_25['predicted_seed'] = seed_values

# Update the main DataFrame with the seeded teams
cbb25.update(top_68_25) 
cbb25 = cbb25.sort_values(by='predicted_seed')

In [177]:
cbb25.dropna(subset = 'predicted_seed').head(20)

,TEAM,CONF,G,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,predicted_seed_score,rank,predicted_seed
40,Mississippi,SEC,4,116.214,100.287,0.846941,49.2208,48.8144,12.1800,24.6190,...,32.2153,46.3267,45.8850,35.2127,35.3248,69.0248,0.46290,8.391466,2.0,1.0
37,Saint Mary's,WCC,4,114.831,98.665,0.851238,53.6111,49.8166,14.7680,15.5261,...,31.6143,54.1117,45.8850,35.0135,38.5309,65.9358,0.89000,8.038424,1.0,1.0
24,BYU,B12,4,116.018,97.751,0.877725,59.8180,49.3153,13.5390,22.2430,...,25.4610,64.6110,43.0500,36.2108,37.3293,71.0105,0.22530,8.505605,3.0,1.0
32,Florida (H) 360 Florida A&M,SEC,4,116.019,98.460,0.868833,56.5480,46.4900,17.5157,20.6830,...,22.9370,66.0800,43.5560,28.7271,34.9238,72.1530,0.81000,8.726513,4.0,1.0
33,Memphis,Amer,3,114.535,97.752,0.860334,59.1260,48.3126,19.5251,18.2164,...,34.4188,52.2161,45.0730,49.1100,35.0239,73.6140,0.97000,8.747872,5.0,2.0
15,St. John's,BE,4,114.930,94.712,0.902716,55.7600,43.3430,18.8217,20.9740,...,28.5890,58.8460,41.7320,33.3158,30.5124,70.7125,0.52400,8.896360,7.0,2.0
26,Michigan,B10,4,116.016,97.853,0.877727,64.4500,42.0280,24.6346,20.4890,...,23.5440,66.4700,43.0500,41.3230,26.7430,70.8124,-0.09900,8.837068,6.0,2.0
28,Ohio St. (H) 256 Evansville,B10,3,115.228,97.245,0.875229,53.7107,38.1400,19.3245,15.9249,...,47.7324,48.4233,37.7800,40.0310,25.7280,69.3225,0.52600,8.903193,8.0,2.0
27,Miami FL,ACC,3,118.280,99.676,0.877028,66.0200,49.4155,11.4400,16.7221,...,36.6215,67.2500,50.5169,42.7160,31.7158,70.3161,0.05830,8.918506,9.0,3.0
31,Pittsburgh,ACC,5,114.534,96.939,0.872132,59.0280,40.6170,12.7190,18.9135,...,29.2105,61.5250,40.4200,37.0860,27.3540,69.5210,0.52700,8.971502,12.0,3.0
6,Tennessee,SEC,4,115.422,91.540,0.935170,65.4300,42.1290,20.0265,19.6109,...,27.9820,67.1600,43.1540,41.6200,27.5590,70.0172,0.81200,8.969528,11.0,3.0
35,Oregon,B10,4,113.243,96.837,0.857936,52.4133,44.5570,15.2770,19.0132,...,22.4290,57.1700,48.2120,29.9244,26.6410,69.6197,0.38400,8.955598,10.0,3.0
16,Kentucky (H) 122 Lipscomb,SEC,3,116.017,95.619,0.902417,57.5400,43.2410,14.5610,14.5295,...,16.5300,55.7930,46.9990,40.0310,25.0160,73.1240,0.95000,9.221745,13.0,4.0
46,Boise St.,MWC,4,112.748,98.358,0.828947,51.7146,42.9350,12.7190,14.2304,...,25.4610,53.8123,47.0100,31.7205,24.3140,68.7266,-0.01860,9.374647,16.0,4.0
2,Gonzaga,WCC,4,122.610,95.722,0.945630,57.9350,44.7610,12.3110,19.7106,...,29.7112,59.2410,49.0138,37.1830,25.3210,71.7680,1.51000,9.245642,14.0,4.0
29,Indiana,B10,3,115.721,97.750,0.874930,61.2110,41.9260,18.0180,18.9135,...,23.6460,62.2180,43.1540,39.2410,26.7430,71.2940,0.40390,9.347940,15.0,4.0
23,Mississippi St.,SEC,4,115.920,97.143,0.884324,55.5640,44.2530,12.3110,23.6300,...,32.5158,59.4400,43.8600,33.3158,30.0111,70.6139,0.62200,9.585346,17.0,5.0
18,Texas,SEC,4,116.215,96.026,0.899319,59.5220,43.1390,11.5500,20.8770,...,27.9820,60.1310,36.6300,38.8510,34.7233,69.8190,-0.37129,9.634565,19.0,5.0
43,Wisconsin,B10,5,115.325,99.980,0.838944,56.4490,49.8166,13.3330,19.2125,...,27.0700,54.7107,48.2120,39.1460,34.6231,68.5281,0.81100,9.627989,18.0,5.0
4,Kansas (H) 172 UNC Wilmington,B12,4,119.430,93.980,0.940850,56.7450,44.5570,12.4150,17.6187,...,31.0131,56.9750,47.4105,37.5710,26.4380,71.5770,1.32000,9.680401,20.0,5.0

In [178]:
# Preprocess the POSTSEASON column in cbb
cbb = cbb[cbb['POSTSEASON'].notnull()]  # Filter rows with POSTSEASON values
label_encoder = LabelEncoder()
cbb['POSTSEASON_LABEL'] = label_encoder.fit_transform(cbb['POSTSEASON'])  # Encode POSTSEASON

# Select features for modeling
postseason_features = [
    'predicted_seed', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D', 'TOR',
    'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O', '3P_D',
    'ADJ_T', 'WAB'
]

# Replace SEED with predicted_seed for cbb
cbb['predicted_seed'] = cbb['SEED']  # Use actual SEED for training

# Define X and y for training
X_postseason = cbb[postseason_features]
y_postseason = cbb['POSTSEASON_LABEL']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_postseason, y_postseason, test_size=0.2, random_state=42
)

# Train a Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=42, n_estimators=100)
rf_classifier.fit(X_train, y_train)

# Evaluate on test data
y_pred = rf_classifier.predict(X_test)
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

# Apply the model to cbb24 data
cbb25_seeded = cbb25.dropna(subset=['predicted_seed'])

X_cbb25 = cbb25_seeded[postseason_features]
postseason_probs_25 = rf_classifier.predict_proba(X_cbb25)

# Define the number of teams per label
label_counts = {
    'Champion': 1,
    'Runner-Up': 1,
    'Final Four': 2,
    'Elite Eight': 4,
    'Sweet Sixteen': 8,
    'Round of 32': 16,
    'Round of 64': 32
}

# Assign labels systematically
num_labels_25 = len(label_counts)
assigned_labels_25 = np.full(len(cbb25_seeded), num_labels_25 - 1)  # Default to lowest label
remaining_teams_25 = list(range(len(cbb25_seeded)))

# Loop through each label, starting with the highest rank (Champion)
for label_idx, (label, count) in enumerate(label_counts.items()):
    # Select top teams based on probabilities for the current label
    if len(remaining_teams_25) == 0:
        break
    label_probs_25 = postseason_probs_25[remaining_teams_25, label_idx]
    top_indices_25 = np.argsort(label_probs_25)[-count:]  # Get indices of top `count` teams
    top_team_indices_25 = [remaining_teams_25[i] for i in top_indices_25]  # Map back to original indices
    for i in top_team_indices_25:
        assigned_labels_25[i] = label_idx
    remaining_teams_25 = [team for team in remaining_teams_25 if team not in top_team_indices_25]  # Exclude assigned teams

# Map assigned labels back to POSTSEASON names
cbb25_seeded['predicted_postseason_label'] = assigned_labels_25

              precision    recall  f1-score   support

         2ND       0.00      0.00      0.00         2
   Champions       0.00      0.00      0.00         1
          E8       0.00      0.00      0.00         8
          F4       0.00      0.00      0.00         7
         R32       0.52      0.28      0.36        40
         R64       0.65      0.77      0.70        66
         R68       0.00      0.00      0.00         5
         S16       0.15      0.71      0.25         7

    accuracy                           0.49       136
   macro avg       0.17      0.22      0.16       136
weighted avg       0.48      0.49      0.46       136

/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_81611/3542001177.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb25_seeded['predicted_postseason_label'] = assigned_labels_25

In [179]:
postseason_mapping = {
    0: 'Winner',
    1: 'Runner-Up',
    2: 'Final Four',
    3: 'Elite Eight',
    4: 'Sweet Sixteen',
    5: 'Round of 32',
    6: 'Round of 64'
}

# Map the numerical labels to their descriptions
cbb25_seeded['predicted_postseason_description'] = cbb25_seeded['predicted_postseason_label'].map(postseason_mapping)

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_81611/863179138.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb25_seeded['predicted_postseason_description'] = cbb25_seeded['predicted_postseason_label'].map(postseason_mapping)

In [180]:
cbb25_seeded.sort_values('predicted_postseason_label').head(16)

,TEAM,CONF,G,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,...,2P_D,3P_O,3P_D,ADJ_T,WAB,predicted_seed_score,rank,predicted_seed,predicted_postseason_label,predicted_postseason_description
1,Duke,ACC,4,118.8500,90.330,0.959020,56.9420,39.0800,13.4360,20.1970,...,39.3140,37.2800,25.7280,70.3158,-0.18103,10.271113,36.0,9.0,0,Winner
2,Gonzaga,WCC,4,122.6100,95.722,0.945630,57.9350,44.7610,12.3110,19.7106,...,49.0138,37.1830,25.3210,71.7680,1.51000,9.245642,14.0,4.0,1,Runner-Up
5,Iowa St.,B12,3,114.2370,90.320,0.937460,54.6860,40.8180,13.3330,28.0200,...,43.0500,31.0221,25.4230,69.7193,0.10750,10.490488,40.0,10.0,2,Final Four
33,Memphis,Amer,3,114.5350,97.752,0.860334,59.1260,48.3126,19.5251,18.2164,...,45.0730,49.1100,35.0239,73.6140,0.97000,8.747872,5.0,2.0,2,Final Four
19,UCLA,B10,4,112.7470,93.760,0.893320,51.1159,40.9200,19.1236,27.4600,...,40.5210,26.4308,27.7640,66.7346,-0.38131,10.331474,37.0,10.0,3,Elite Eight
29,Indiana,B10,3,115.7210,97.750,0.874930,61.2110,41.9260,18.0180,18.9135,...,43.1540,39.2410,26.7430,71.2940,0.40390,9.347940,15.0,4.0,3,Elite Eight
70,Virginia,ACC,3,108.4105,96.835,0.786671,59.1260,41.2220,18.9224,17.3203,...,37.5700,44.6900,30.0111,64.6363,0.44300,10.192341,32.0,8.0,3,Elite Eight
4,Kansas (H) 172 UNC Wilmington,B12,4,119.4300,93.980,0.940850,56.7450,44.5570,12.4150,17.6187,...,47.4105,37.5710,26.4380,71.5770,1.32000,9.680401,20.0,5.0,3,Elite Eight
22,Marquette (H) 15 Purdue,BE,4,114.0390,95.417,0.886423,52.8125,48.0116,12.7190,25.3130,...,50.0161,30.4234,30.1115,71.3860,1.04000,10.089092,28.0,7.0,4,Sweet Sixteen
23,Mississippi St.,SEC,4,115.9200,97.143,0.884324,55.5640,44.2530,12.3110,23.6300,...,43.8600,33.3158,30.0111,70.6139,0.62200,9.585346,17.0,5.0,4,Sweet Sixteen
11,Arizona,B12,3,115.2290,94.210,0.909512,50.2183,48.1119,13.6430,20.6830,...,45.1750,27.4295,34.8237,74.6600,-0.29112,10.491407,42.0,11.0,4,Sweet Sixteen
52,LSU (H) 300 Charleston Southern,SEC,3,110.4770,96.940,0.817453,56.3520,39.1900,20.1267,16.8214,...,45.3780,32.1197,16.4100,71.0109,0.71300,10.891284,52.0,13.0,4,Sweet Sixteen
28,Ohio St. (H) 256 Evansville,B10,3,115.2280,97.245,0.875229,53.7107,38.1400,19.3245,15.9249,...,37.7800,40.0310,25.7280,69.3225,0.52600,8.903193,8.0,2.0,4,Sweet Sixteen
38,VCU,A10,4,111.2670,95.721,0.849239,54.0101,37.9300,19.9261,25.6100,...,39.5160,34.0151,22.6500,70.0174,0.28460,11.231346,59.0,15.0,4,Sweet Sixteen
58,SMU,ACC,5,114.1380,101.097,0.802759,54.7820,43.7470,16.0109,21.6620,...,40.7230,38.9490,32.2170,72.5370,-0.36126,11.365800,63.0,16.0,4,Sweet Sixteen
13,Connecticut (H) 348 Texas A&M Commerce,BE,3,114.6320,94.290,0.905214,61.7800,39.6120,14.6640,21.5650,...,36.7400,37.0860,30.6127,67.2333,0.07810,10.404095,39.0,10.0,4,Sweet Sixteen

In [181]:
from datetime import datetime
current_date = datetime.now().strftime("%Y%m%d")
file_name = f"cbb25_seeded_{current_date}.csv"
cbb25_seeded.to_csv(file_name, index=False)