In [264]:
import numpy as np 
import pandas as pd

In [265]:
cbb = pd.read_csv('/Users/visheshgupta/Desktop/Final_Project_DE/archive/cbb.csv')

In [266]:
cbb.columns

Index(['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'POSTSEASON', 'SEED', 'YEAR'],
      dtype='object')

In [267]:
cbb24 = pd.read_csv('/Users/visheshgupta/Desktop/Final_Project_DE/archive/cbb24.csv')

In [268]:
cbb24.columns

Index(['RK', 'TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG%',
       'EFGD%', 'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D',
       '3P_O', '3P_D', 'ADJ_T', 'WAB', 'SEED'],
      dtype='object')

In [269]:
cbb24['EFG_O'] = cbb24['EFG%']
cbb24['EFG_D'] = cbb24['EFGD%']
cbb24 = cbb24[['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'SEED']]

In [270]:
cbb24

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,SEED
0,Houston,B12,34,30,119.2,85.5,0.9785,49.7,44.0,13.7,...,30.2,29.9,39.0,48.4,43.4,34.7,30.0,63.3,10.6,1.0
1,Connecticut,BE,34,31,127.1,93.6,0.9712,57.1,45.1,14.9,...,26.8,33.3,32.5,58.5,43.7,36.7,31.9,64.6,11.3,1.0
2,Purdue,B10,33,29,126.2,94.7,0.9644,56.0,47.7,16.5,...,24.7,42.8,23.0,53.2,48.1,40.8,31.4,67.6,11.0,1.0
3,Iowa St.,B12,34,27,113.6,86.5,0.9583,51.9,47.1,15.7,...,29.4,36.1,35.2,51.7,46.9,34.9,31.5,67.6,6.9,2.0
4,Auburn,SEC,34,27,120.7,92.1,0.9573,54.1,43.4,14.9,...,30.3,38.2,41.0,54.9,42.8,35.2,29.8,69.8,5.5,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,Stonehill,NEC,30,4,90.3,114.2,0.0629,46.7,52.7,19.5,...,31.0,22.6,29.4,47.9,51.7,30.1,35.9,68.1,-22.0,NaN
358,St. Francis PA,NEC,28,8,93.1,118.1,0.0608,47.2,53.0,21.2,...,31.3,32.6,35.4,45.7,52.9,33.2,35.4,65.4,-18.6,NaN
359,IUPUI,Horz,29,6,92.1,116.9,0.0607,46.5,58.2,21.3,...,35.5,33.2,33.4,49.5,59.0,24.7,38.0,67.3,-21.6,NaN
360,Coppin St.,MEAC,29,2,85.1,111.1,0.0445,42.1,51.3,22.9,...,38.6,31.1,38.3,41.9,51.0,28.3,34.5,66.3,-22.9,NaN
361,Mississippi Valley St.,SWAC,31,1,85.4,116.2,0.0283,42.5,55.6,24.0,...,35.7,33.0,41.6,41.9,55.6,29.2,37.0,64.5,-22.7,NaN

In [271]:
cbb

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,...,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,...,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,...,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,...,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,...,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3518,Toledo,MAC,34,27,119.9,109.6,0.7369,56.3,52.9,13.6,...,27.5,54.6,52.1,39.7,36.1,69.5,-1.2,NaN,NaN,2023
3519,Liberty,ASun,33,27,111.4,97.3,0.8246,55.5,49.3,16.0,...,27.8,56.4,48.6,36.4,33.6,64.4,-2.0,NaN,NaN,2023
3520,Utah Valley,WAC,34,28,107.1,94.6,0.8065,51.7,44.0,19.3,...,28.7,52.5,42.8,33.4,31.1,69.8,-0.3,NaN,NaN,2023
3521,UAB,CUSA,38,29,112.4,97.0,0.8453,50.3,47.3,17.3,...,28.9,48.8,47.2,35.6,31.6,70.7,-0.5,NaN,NaN,2023
3522,North Texas,CUSA,36,31,110.0,93.8,0.8622,51.2,44.5,19.8,...,40.2,49.6,44.2,35.7,30.1,58.7,1.1,NaN,NaN,2023

In [272]:
cbb.to_csv('train_data.csv', index=False)

In [273]:
cbb24.to_csv('test_data.csv', index=False)

In [274]:
#dummy data:

In [275]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.barttorvik.com/"
response = requests.get(url)

# Parse the HTML
soup = BeautifulSoup(response.text, "html.parser")

# Inspect the page structure and find the table or relevant data
# Example: Extracting table data
table = soup.find("table")
rows = table.find_all("tr")

data = []
for row in rows:
    cols = row.find_all("td")
    cols = [ele.text.strip() for ele in cols]
    data.append(cols)

# Convert to DataFrame and save as CSV
df = pd.DataFrame(data)
df = df.dropna(how="all").reset_index(drop=True)

df.columns = ['RK', 'TEAM', 'CONF', 'G', 'REC', 'ADJOE', 'ADJDE', 'BARTHAG', "EFG_O", "EFG_D", 'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', "2P_O", "2P_D", "3P_O", "3P_D", '3PR', '3PRD', 'ADJ_T', 'WAB']
df = df[[
    "TEAM", "CONF", "G", "ADJOE", "ADJDE", "BARTHAG", 
    "EFG_O", "EFG_D", "TOR", "TORD", "ORB", "DRB", "FTR", "FTRD", 
    "2P_O", "2P_D", "3P_O", "3P_D", "ADJ_T", "WAB"
]]
df.to_csv("current_cbb_live_data.csv", index=False)

In [276]:
df.columns

Index(['TEAM', 'CONF', 'G', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB'],
      dtype='object')

In [277]:

cbb.columns

Index(['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'POSTSEASON', 'SEED', 'YEAR'],
      dtype='object')

In [278]:
cbb24.columns

Index(['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'SEED'],
      dtype='object')

In [279]:
len(cbb.columns)

24

In [280]:
len(cbb24.columns)

22

In [281]:
'''   
# columns that we are missing in our scrapped date:
1. W : no of  games a team won
2. POST SEASON: What position they finished. This is what we are predciting so we are good
3. Seed: We cannot know this information 
4. Year: This is Trivial 
'''

'   \n# columns that we are missing in our scrapped date:\n1. W : no of  games a team won\n2. POST SEASON: What position they finished. This is what we are predciting so we are good\n3. Seed: We cannot know this information \n4. Year: This is Trivial \n'

In [282]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

cbb_model = cbb[cbb['SEED'].notnull()]

cbb_model['SEED'] = cbb_model['SEED'].astype(int)

features = [
    'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D', 'TOR', 'TORD', 'ORB',
    'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O', '3P_D', 'ADJ_T', 'WAB'
]
X = cbb_model[features]
y = cbb_model['SEED']

cbb24_seedless = cbb24[features]  

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
cbb24_scaled = scaler.transform(cbb24_seedless)

models = {
    'Linear Regression': LinearRegression(),
    'Random Forest': RandomForestRegressor(random_state=42, n_estimators=100),
    'XGBoost': XGBRegressor(random_state=42)
}

results = {}
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_pred_rounded = np.round(y_pred).clip(1, 16)  # Clip predictions to valid seed range
    mae = mean_absolute_error(y_test, y_pred_rounded)
    results[model_name] = mae

# Predict seeds for cbb24 using the best-performing model
best_model_name = min(results, key=results.get)
best_model = models[best_model_name]
cbb24_predictions = best_model.predict(cbb24_scaled)
cbb24['predicted_seed_score'] = cbb24_predictions  # Store raw predictions for ranking

# Rank teams based on predicted seed scores
cbb24['rank'] = cbb24['predicted_seed_score'].rank(method='min', ascending=True)

# Assign seeds to top 64 teams
cbb24['predicted_seed'] = np.nan  # Initialize with NaN
top_64 = cbb24.nsmallest(64, 'predicted_seed_score')  # Select top 64 teams


seed_values = [seed for seed in range(1, 17) for _ in range(4)]  # 16 seeds, 4 teams each
top_64['predicted_seed'] = seed_values
cbb24.update(top_64) 
cbb24 = cbb24.sort_values(by='predicted_seed')

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_54319/3395395553.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb_model['SEED'] = cbb_model['SEED'].astype(int)

In [283]:
results

{'Linear Regression': 1.0514705882352942,
 'Random Forest': 1.0808823529411764,
 'XGBoost': 1.1544117647058822}

In [284]:
cbb24.sort_values('SEED')

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,SEED,predicted_seed_score,rank,predicted_seed
0,Houston,B12,34,30,119.2,85.5,0.9785,49.7,44.0,13.7,...,48.4,43.4,34.7,30.0,63.3,10.6,1.0,-1.690100,1.0,1.0
1,Connecticut,BE,34,31,127.1,93.6,0.9712,57.1,45.1,14.9,...,58.5,43.7,36.7,31.9,64.6,11.3,1.0,-1.668222,2.0,1.0
2,Purdue,B10,33,29,126.2,94.7,0.9644,56.0,47.7,16.5,...,53.2,48.1,40.8,31.4,67.6,11.0,1.0,-0.886746,3.0,1.0
8,North Carolina,ACC,34,27,116.8,93.2,0.9305,51.3,46.4,14.4,...,50.3,46.0,35.4,31.4,70.4,6.6,1.0,4.142559,8.0,2.0
3,Iowa St.,B12,34,27,113.6,86.5,0.9583,51.9,47.1,15.7,...,51.7,46.9,34.9,31.5,67.6,6.9,2.0,3.199879,4.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,Stonehill,NEC,30,4,90.3,114.2,0.0629,46.7,52.7,19.5,...,47.9,51.7,30.1,35.9,68.1,-22.0,NaN,26.257163,358.0,NaN
358,St. Francis PA,NEC,28,8,93.1,118.1,0.0608,47.2,53.0,21.2,...,45.7,52.9,33.2,35.4,65.4,-18.6,NaN,25.695877,355.0,NaN
359,IUPUI,Horz,29,6,92.1,116.9,0.0607,46.5,58.2,21.3,...,49.5,59.0,24.7,38.0,67.3,-21.6,NaN,26.396365,359.0,NaN
360,Coppin St.,MEAC,29,2,85.1,111.1,0.0445,42.1,51.3,22.9,...,41.9,51.0,28.3,34.5,66.3,-22.9,NaN,26.657868,360.0,NaN
361,Mississippi Valley St.,SWAC,31,1,85.4,116.2,0.0283,42.5,55.6,24.0,...,41.9,55.6,29.2,37.0,64.5,-22.7,NaN,27.959741,362.0,NaN

In [285]:
cbb['POSTSEASON'].unique()

array(['2ND', 'Champions', 'E8', 'F4', nan, 'R32', 'R64', 'R68', 'S16'],
      dtype=object)

In [286]:
cbb[cbb['POSTSEASON'] == 'Champions']

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
7,Duke,ACC,39,35,125.2,90.6,0.9764,56.6,46.5,16.3,...,23.9,55.9,46.3,38.7,31.4,66.4,10.7,Champions,1.0,2015
8,Virginia,ACC,38,35,123.0,89.9,0.9736,55.2,44.7,14.7,...,26.3,52.5,45.7,39.5,28.9,60.7,11.1,Champions,1.0,2019
9,North Carolina,ACC,39,33,121.0,91.5,0.9615,51.7,48.1,16.2,...,31.6,51.0,46.3,35.5,33.9,72.8,8.4,Champions,1.0,2017
10,Villanova,BE,40,35,123.1,90.9,0.9703,56.1,46.7,16.3,...,30.0,57.4,44.1,36.2,33.9,66.7,8.9,Champions,2.0,2016
11,Villanova,BE,40,36,128.4,94.1,0.9725,59.5,48.5,15.0,...,26.7,59.0,49.0,40.1,31.7,69.6,10.6,Champions,1.0,2018
12,Connecticut,Amer,40,32,112.5,91.3,0.9171,51.5,44.6,17.3,...,35.7,48.1,42.2,38.7,33.0,64.8,4.7,Champions,7.0,2014
13,Louisville,BE,40,35,115.9,84.5,0.9743,50.6,44.8,18.3,...,34.9,50.8,43.4,33.3,31.8,67.1,9.0,Champions,1.0,2013
2456,Baylor,B12,24,22,123.2,94.5,0.9548,57.5,49.1,17.6,...,31.7,54.1,48.1,41.8,34.0,68.8,6.6,Champions,1.0,2021
2803,Kansas,B12,40,34,119.8,91.3,0.9580,53.8,45.8,17.3,...,27.7,53.6,46.4,36.1,29.8,69.1,10.4,Champions,1.0,2022
3172,Connecticut,BE,39,31,121.5,91.2,0.9643,53.9,44.4,18.9,...,37.8,53.6,44.4,36.3,29.7,66.7,5.0,Champions,4.0,2023

In [287]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
import numpy as np

# Preprocess the POSTSEASON column in cbb
cbb = cbb[cbb['POSTSEASON'].notnull()]  # Filter rows with POSTSEASON values
label_encoder = LabelEncoder()
cbb['POSTSEASON_LABEL'] = label_encoder.fit_transform(cbb['POSTSEASON'])  # Encode POSTSEASON

# Select features for modeling
postseason_features = [
    'predicted_seed', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D', 'TOR',
    'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O', '3P_D',
    'ADJ_T', 'WAB'
]

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_54319/2602970668.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb['POSTSEASON_LABEL'] = label_encoder.fit_transform(cbb['POSTSEASON'])  # Encode POSTSEASON

In [288]:


# Replace SEED with predicted_seed for cbb
cbb['predicted_seed'] = cbb['SEED']  # Use actual SEED for training

# Define X and y for training
X_postseason = cbb[postseason_features]
y_postseason = cbb['POSTSEASON_LABEL']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_postseason, y_postseason, test_size=0.2, random_state=42
)

# Train a Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=42, n_estimators=100)
rf_classifier.fit(X_train, y_train)

# Evaluate on test data
y_pred = rf_classifier.predict(X_test)
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

Classification Report:
              precision    recall  f1-score   support

         2ND       0.00      0.00      0.00         2
   Champions       0.00      0.00      0.00         1
          E8       0.00      0.00      0.00         8
          F4       0.00      0.00      0.00         7
         R32       0.52      0.28      0.36        40
         R64       0.65      0.77      0.70        66
         R68       0.00      0.00      0.00         5
         S16       0.15      0.71      0.25         7

    accuracy                           0.49       136
   macro avg       0.17      0.22      0.16       136
weighted avg       0.48      0.49      0.46       136

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_54319/2382289260.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb['predicted_seed'] = cbb['SEED']  # Use actual SEED for training
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [289]:
cbb24_seeded = cbb24.dropna(subset=['predicted_seed'])
cbb24_seeded

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,SEED,predicted_seed_score,rank,predicted_seed
0,Houston,B12,34,30,119.2,85.5,0.9785,49.7,44.0,13.7,...,48.4,43.4,34.7,30.0,63.3,10.6,1.0,-1.690100,1.0,1.0
1,Connecticut,BE,34,31,127.1,93.6,0.9712,57.1,45.1,14.9,...,58.5,43.7,36.7,31.9,64.6,11.3,1.0,-1.668222,2.0,1.0
2,Purdue,B10,33,29,126.2,94.7,0.9644,56.0,47.7,16.5,...,53.2,48.1,40.8,31.4,67.6,11.0,1.0,-0.886746,3.0,1.0
3,Iowa St.,B12,34,27,113.6,86.5,0.9583,51.9,47.1,15.7,...,51.7,46.9,34.9,31.5,67.6,6.9,2.0,3.199879,4.0,1.0
4,Auburn,SEC,34,27,120.7,92.1,0.9573,54.1,43.4,14.9,...,54.9,42.8,35.2,29.8,69.8,5.5,4.0,3.628903,6.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,Drake,MVC,33,28,114.8,100.2,0.8283,54.9,51.0,13.9,...,55.1,51.9,36.5,33.0,67.8,1.7,10.0,10.321549,58.0,15.0
33,Wake Forest,ACC,33,20,116.5,99.0,0.8660,54.7,48.9,15.6,...,54.0,48.8,37.2,32.6,68.0,-1.3,NaN,10.755381,63.0,16.0
61,Xavier,BE,33,16,111.4,98.7,0.8008,49.0,49.6,16.2,...,48.0,49.4,34.0,33.3,70.9,-2.1,NaN,10.888149,64.0,16.0
62,North Carolina St.,ACC,36,22,114.0,101.2,0.7981,50.7,50.5,13.7,...,50.1,49.5,34.6,34.9,67.9,-0.6,11.0,10.616000,61.0,16.0
69,Grand Canyon,WAC,32,29,111.1,99.8,0.7733,52.0,45.9,17.8,...,52.3,44.4,34.4,32.6,68.0,1.3,12.0,10.647619,62.0,16.0

In [290]:
X_cbb24 = cbb24_seeded[postseason_features]

In [291]:
postseason_probs = rf_classifier.predict_proba(X_cbb24)

In [292]:
# Ensure all labels are represented
num_teams = len(cbb24_seeded)
label_counts = {
    'Champion': 1,
    'Runner-Up': 1,
    'Final Four': 2,
    'Elite Eight': 4,
    'Sweet Sixteen': 8,
    'Round of 32': 16,
    'Round of 64': 32
}

# Assign labels systematically
assigned_labels = np.zeros(num_teams, dtype=int)  # Initialize label assignments
for label_idx, count in enumerate(label_counts.values()):
    # Rank teams by probabilities for this label
    label_probs = postseason_probs[:, label_idx]
    top_teams = np.argsort(label_probs)[-count:]  # Get indices of top teams
    assigned_labels[top_teams] = label_idx  # Assign the current label

In [293]:

# Map assigned labels back to POSTSEASON names
cbb24_seeded['predicted_postseason_label'] = assigned_labels
cbb24_seeded['predicted_postseason'] = label_encoder.inverse_transform(cbb24_seeded['predicted_postseason_label'])

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_54319/2521100994.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb24_seeded['predicted_postseason_label'] = assigned_labels
/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_54319/2521100994.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb24_seeded['predicted_postseason'] = label_encoder.inverse_transform(cbb24_seeded['predicted_postseason_label'])

In [296]:
cbb24_seeded.sort_values('predicted_postseason_label').head(20)

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,3P_O,3P_D,ADJ_T,WAB,SEED,predicted_seed_score,rank,predicted_seed,predicted_postseason_label,predicted_postseason
32,TCU,B12,33,21,114.5,97.1,0.8690,51.9,50.3,17.9,...,35.6,32.8,69.9,1.3,9.0,8.899182,32.0,8.0,0,2ND
13,Gonzaga,WCC,31,25,121.3,98.6,0.9151,56.7,47.3,14.0,...,35.5,34.0,69.1,2.5,5.0,7.472296,22.0,6.0,0,2ND
17,BYU,B12,33,23,120.6,99.0,0.9067,55.1,48.0,15.2,...,34.8,31.8,69.0,2.9,6.0,7.085692,20.0,5.0,0,2ND
26,Colorado,P12,34,24,117.2,98.0,0.8866,55.3,49.3,18.1,...,39.4,31.9,67.7,1.7,10.0,8.623984,28.0,7.0,0,2ND
36,Nevada,MWC,32,26,115.1,98.0,0.8632,53.3,48.2,15.0,...,36.5,31.3,66.8,2.7,10.0,9.105728,35.0,9.0,0,2ND
38,Washington St.,P12,33,24,112.8,96.6,0.8556,52.1,47.3,16.1,...,34.0,32.0,64.9,1.9,7.0,9.112962,37.0,10.0,0,2ND
10,Duke,ACC,32,24,120.8,96.8,0.9272,55.2,49.0,14.3,...,37.7,32.6,66.9,3.3,4.0,6.598609,16.0,4.0,0,2ND
16,Baylor,B12,32,23,122.2,99.9,0.9103,55.6,51.3,17.7,...,39.4,33.5,65.7,5.1,3.0,5.700315,13.0,4.0,0,2ND
18,Wisconsin,B10,35,22,119.8,98.8,0.9018,52.4,52.2,14.6,...,34.8,37.1,65.0,3.3,5.0,6.350392,15.0,4.0,0,2ND
15,Kansas,B12,31,22,113.5,92.7,0.9111,53.4,47.6,16.4,...,33.3,33.8,68.9,4.3,4.0,5.689720,12.0,3.0,0,2ND
9,Creighton,BE,32,23,120.6,96.5,0.9289,57.5,46.4,15.3,...,36.1,32.2,66.9,4.4,3.0,4.773179,11.0,3.0,0,2ND
6,Tennessee,SEC,32,24,115.6,91.2,0.9382,51.5,45.4,14.6,...,34.2,31.4,69.2,5.8,2.0,4.332457,10.0,3.0,0,2ND
5,Arizona,P12,33,25,121.5,93.6,0.9526,55.0,48.7,16.1,...,37.1,33.4,72.0,4.9,2.0,4.178061,9.0,3.0,0,2ND
8,North Carolina,ACC,34,27,116.8,93.2,0.9305,51.3,46.4,14.4,...,35.4,31.4,70.4,6.6,1.0,4.142559,8.0,2.0,0,2ND
31,Villanova,BE,33,18,110.4,93.5,0.8710,50.7,48.2,14.5,...,34.0,32.7,63.3,-1.1,NaN,10.247187,54.0,14.0,0,2ND
4,Auburn,SEC,34,27,120.7,92.1,0.9573,54.1,43.4,14.9,...,35.2,29.8,69.8,5.5,4.0,3.628903,6.0,2.0,0,2ND
21,Nebraska,B10,33,23,115.7,95.6,0.8999,53.2,46.3,15.9,...,35.8,31.9,68.7,2.4,8.0,7.174471,21.0,6.0,0,2ND
24,Kentucky,SEC,32,23,123.0,102.2,0.8934,57.4,49.5,14.2,...,41.2,32.6,72.5,2.9,3.0,7.539180,23.0,6.0,0,2ND
2,Purdue,B10,33,29,126.2,94.7,0.9644,56.0,47.7,16.5,...,40.8,31.4,67.6,11.0,1.0,-0.886746,3.0,1.0,1,Champions
3,Iowa St.,B12,34,27,113.6,86.5,0.9583,51.9,47.1,15.7,...,34.9,31.5,67.6,6.9,2.0,3.199879,4.0,1.0,2,E8