In [220]:
import numpy as np 
import pandas as pd 
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

In [221]:
cbb = pd.read_csv('/Users/visheshgupta/Desktop/Final_Project_DE/archive/cbb.csv')

In [222]:
cbb.columns

Index(['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'POSTSEASON', 'SEED', 'YEAR'],
      dtype='object')

In [223]:
cbb24 = pd.read_csv('/Users/visheshgupta/Desktop/Final_Project_DE/archive/cbb24.csv')

In [224]:
cbb24.columns

Index(['RK', 'TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG%',
       'EFGD%', 'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D',
       '3P_O', '3P_D', 'ADJ_T', 'WAB', 'SEED'],
      dtype='object')

In [225]:
cbb24['EFG_O'] = cbb24['EFG%']
cbb24['EFG_D'] = cbb24['EFGD%']
cbb24 = cbb24[['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'SEED']]

In [226]:
cbb24

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,SEED
0,Houston,B12,34,30,119.2,85.5,0.9785,49.7,44.0,13.7,...,30.2,29.9,39.0,48.4,43.4,34.7,30.0,63.3,10.6,1.0
1,Connecticut,BE,34,31,127.1,93.6,0.9712,57.1,45.1,14.9,...,26.8,33.3,32.5,58.5,43.7,36.7,31.9,64.6,11.3,1.0
2,Purdue,B10,33,29,126.2,94.7,0.9644,56.0,47.7,16.5,...,24.7,42.8,23.0,53.2,48.1,40.8,31.4,67.6,11.0,1.0
3,Iowa St.,B12,34,27,113.6,86.5,0.9583,51.9,47.1,15.7,...,29.4,36.1,35.2,51.7,46.9,34.9,31.5,67.6,6.9,2.0
4,Auburn,SEC,34,27,120.7,92.1,0.9573,54.1,43.4,14.9,...,30.3,38.2,41.0,54.9,42.8,35.2,29.8,69.8,5.5,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,Stonehill,NEC,30,4,90.3,114.2,0.0629,46.7,52.7,19.5,...,31.0,22.6,29.4,47.9,51.7,30.1,35.9,68.1,-22.0,NaN
358,St. Francis PA,NEC,28,8,93.1,118.1,0.0608,47.2,53.0,21.2,...,31.3,32.6,35.4,45.7,52.9,33.2,35.4,65.4,-18.6,NaN
359,IUPUI,Horz,29,6,92.1,116.9,0.0607,46.5,58.2,21.3,...,35.5,33.2,33.4,49.5,59.0,24.7,38.0,67.3,-21.6,NaN
360,Coppin St.,MEAC,29,2,85.1,111.1,0.0445,42.1,51.3,22.9,...,38.6,31.1,38.3,41.9,51.0,28.3,34.5,66.3,-22.9,NaN
361,Mississippi Valley St.,SWAC,31,1,85.4,116.2,0.0283,42.5,55.6,24.0,...,35.7,33.0,41.6,41.9,55.6,29.2,37.0,64.5,-22.7,NaN

In [227]:
cbb

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,...,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,...,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,...,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,...,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,...,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3518,Toledo,MAC,34,27,119.9,109.6,0.7369,56.3,52.9,13.6,...,27.5,54.6,52.1,39.7,36.1,69.5,-1.2,NaN,NaN,2023
3519,Liberty,ASun,33,27,111.4,97.3,0.8246,55.5,49.3,16.0,...,27.8,56.4,48.6,36.4,33.6,64.4,-2.0,NaN,NaN,2023
3520,Utah Valley,WAC,34,28,107.1,94.6,0.8065,51.7,44.0,19.3,...,28.7,52.5,42.8,33.4,31.1,69.8,-0.3,NaN,NaN,2023
3521,UAB,CUSA,38,29,112.4,97.0,0.8453,50.3,47.3,17.3,...,28.9,48.8,47.2,35.6,31.6,70.7,-0.5,NaN,NaN,2023
3522,North Texas,CUSA,36,31,110.0,93.8,0.8622,51.2,44.5,19.8,...,40.2,49.6,44.2,35.7,30.1,58.7,1.1,NaN,NaN,2023

In [228]:
cbb.to_csv('train_data.csv', index=False)

In [229]:
cbb24.to_csv('test_data.csv', index=False)

In [230]:
#dummy data:

In [231]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.barttorvik.com/"
response = requests.get(url)

# Parse the HTML
soup = BeautifulSoup(response.text, "html.parser")

# Inspect the page structure and find the table or relevant data
# Example: Extracting table data
table = soup.find("table")
rows = table.find_all("tr")

data = []
for row in rows:
    cols = row.find_all("td")
    cols = [ele.text.strip() for ele in cols]
    data.append(cols)

# Convert to DataFrame and save as CSV
df = pd.DataFrame(data)
df = df.dropna(how="all").reset_index(drop=True)

df.columns = ['RK', 'TEAM', 'CONF', 'G', 'REC', 'ADJOE', 'ADJDE', 'BARTHAG', "EFG_O", "EFG_D", 'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', "2P_O", "2P_D", "3P_O", "3P_D", '3PR', '3PRD', 'ADJ_T', 'WAB']
df = df[[
    "TEAM", "CONF", "G", "ADJOE", "ADJDE", "BARTHAG", 
    "EFG_O", "EFG_D", "TOR", "TORD", "ORB", "DRB", "FTR", "FTRD", 
    "2P_O", "2P_D", "3P_O", "3P_D", "ADJ_T", "WAB"
]]
df.to_csv("current_cbb_live_data.csv", index=False)

In [232]:
df.columns

Index(['TEAM', 'CONF', 'G', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB'],
      dtype='object')

In [233]:

cbb.columns

Index(['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'POSTSEASON', 'SEED', 'YEAR'],
      dtype='object')

In [234]:
cbb24.columns

Index(['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'SEED'],
      dtype='object')

In [235]:
len(cbb.columns)

24

In [236]:
len(cbb24.columns)

22

In [237]:
'''   
# columns that we are missing in our scrapped date:
1. W : no of  games a team won
2. POST SEASON: What position they finished. This is what we are predciting so we are good
3. Seed: We cannot know this information 
4. Year: This is Trivial 
'''

'   \n# columns that we are missing in our scrapped date:\n1. W : no of  games a team won\n2. POST SEASON: What position they finished. This is what we are predciting so we are good\n3. Seed: We cannot know this information \n4. Year: This is Trivial \n'

In [238]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

cbb_model = cbb[cbb['SEED'].notnull()]

cbb_model['SEED'] = cbb_model['SEED'].astype(int)

features = [
    'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D', 'TOR', 'TORD', 'ORB',
    'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O', '3P_D', 'ADJ_T', 'WAB'
]
X = cbb_model[features]
y = cbb_model['SEED']

cbb24_seedless = cbb24[features]  

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
cbb24_scaled = scaler.transform(cbb24_seedless)

models = {
    'Linear Regression': LinearRegression(),
    'Random Forest': RandomForestRegressor(random_state=42, n_estimators=100),
    'XGBoost': XGBRegressor(random_state=42)
}

results = {}
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_pred_rounded = np.round(y_pred).clip(1, 16)  # Clip predictions to valid seed range
    mae = mean_absolute_error(y_test, y_pred_rounded)
    results[model_name] = mae

# Predict seeds for cbb24 using the best-performing model
best_model_name = max(results, key=results.get)
best_model = models[best_model_name]
cbb24_predictions = best_model.predict(cbb24_scaled)
cbb24['predicted_seed_score'] = cbb24_predictions  # Store raw predictions for ranking

# Rank teams based on predicted seed scores
cbb24['rank'] = cbb24['predicted_seed_score'].rank(method='min', ascending=True)

# Assign seeds to top 68 teams
cbb24['predicted_seed'] = np.nan  # Initialize with NaN
top_68 = cbb24.nsmallest(68, 'predicted_seed_score')  # Select top 68 teams

# Create seed values for 68 teams
seed_values = []
for seed in range(1, 17):
    if seed == 11 or seed == 16:
        seed_values.extend([seed] * 6)  # 6 teams for seeds 11 and 16
    else:
        seed_values.extend([seed] * 4)  # 4 teams for other seeds

# Assign seeds to the top 68 teams
top_68['predicted_seed'] = seed_values

# Update the main DataFrame with the seeded teams
cbb24.update(top_68) 
cbb24 = cbb24.sort_values(by='predicted_seed')

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_64147/150274500.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb_model['SEED'] = cbb_model['SEED'].astype(int)

In [239]:
results

{'Linear Regression': 1.0514705882352942,
 'Random Forest': 1.0808823529411764,
 'XGBoost': 1.1544117647058822}

In [240]:
cbb['POSTSEASON'].unique()

array(['2ND', 'Champions', 'E8', 'F4', nan, 'R32', 'R64', 'R68', 'S16'],
      dtype=object)

In [243]:
# Preprocess the POSTSEASON column in cbb
cbb = cbb[cbb['POSTSEASON'].notnull()]  # Filter rows with POSTSEASON values
label_encoder = LabelEncoder()
cbb['POSTSEASON_LABEL'] = label_encoder.fit_transform(cbb['POSTSEASON'])  # Encode POSTSEASON

# Select features for modeling
postseason_features = [
    'predicted_seed', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D', 'TOR',
    'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O', '3P_D',
    'ADJ_T', 'WAB'
]

# Replace SEED with predicted_seed for cbb
cbb['predicted_seed'] = cbb['SEED']  # Use actual SEED for training

# Define X and y for training
X_postseason = cbb[postseason_features]
y_postseason = cbb['POSTSEASON_LABEL']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_postseason, y_postseason, test_size=0.2, random_state=42
)

# Train a Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=42, n_estimators=100)
rf_classifier.fit(X_train, y_train)

# Evaluate on test data
y_pred = rf_classifier.predict(X_test)
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

# Apply the model to cbb24 data
cbb24_seeded = cbb24.dropna(subset=['predicted_seed'])

X_cbb24 = cbb24_seeded[postseason_features]
postseason_probs = rf_classifier.predict_proba(X_cbb24)

# Define the number of teams per label
label_counts = {
    'Champion': 1,
    'Runner-Up': 1,
    'Final Four': 2,
    'Elite Eight': 4,
    'Sweet Sixteen': 8,
    'Round of 32': 16,
    'Round of 64': 32
}

# Assign labels systematically
num_labels = len(label_counts)
assigned_labels = np.full(len(cbb24_seeded), num_labels - 1)  # Default to lowest label
remaining_teams = list(range(len(cbb24_seeded)))

# Loop through each label, starting with the highest rank (Champion)
for label_idx, (label, count) in enumerate(label_counts.items()):
    # Select top teams based on probabilities for the current label
    if len(remaining_teams) == 0:
        break
    label_probs = postseason_probs[remaining_teams, label_idx]
    top_indices = np.argsort(label_probs)[-count:]  # Get indices of top `count` teams
    top_team_indices = [remaining_teams[i] for i in top_indices]  # Map back to original indices
    for i in top_team_indices:
        assigned_labels[i] = label_idx
    remaining_teams = [team for team in remaining_teams if team not in top_team_indices]  # Exclude assigned teams

# Map assigned labels back to POSTSEASON names
cbb24_seeded['predicted_postseason_label'] = assigned_labels

              precision    recall  f1-score   support

         2ND       0.00      0.00      0.00         2
   Champions       0.00      0.00      0.00         1
          E8       0.00      0.00      0.00         8
          F4       0.00      0.00      0.00         7
         R32       0.52      0.28      0.36        40
         R64       0.65      0.77      0.70        66
         R68       0.00      0.00      0.00         5
         S16       0.15      0.71      0.25         7

    accuracy                           0.49       136
   macro avg       0.17      0.22      0.16       136
weighted avg       0.48      0.49      0.46       136

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_64147/4232653574.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb['POSTSEASON_LABEL'] = label_encoder.fit_transform(cbb['POSTSEASON'])  # Encode POSTSEASON
/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_64147/4232653574.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb['predicted_seed'] = cbb['SEED']  # Use actual SEED for training
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_64147/4232653574.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb24_seeded['predicted_postseason_label'] = assigned_labels

In [244]:
postseason_mapping = {
    0: 'Winner',
    1: 'Runner-Up',
    2: 'Final Four',
    3: 'Elite Eight',
    4: 'Sweet Sixteen',
    5: 'Round of 32',
    6: 'Round of 64'
}

# Map the numerical labels to their descriptions
cbb24_seeded['predicted_postseason_description'] = cbb24_seeded['predicted_postseason_label'].map(postseason_mapping)

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_64147/3013661406.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb24_seeded['predicted_postseason_description'] = cbb24_seeded['predicted_postseason_label'].map(postseason_mapping)

In [245]:
cbb24_seeded.sort_values('predicted_postseason_label').head(16)

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,3P_O,3P_D,ADJ_T,WAB,SEED,predicted_seed_score,rank,predicted_seed,predicted_postseason_label,predicted_postseason_description
1,Connecticut,BE,34,31,127.1,93.6,0.9712,57.1,45.1,14.9,...,36.7,31.9,64.6,11.30,1.0,1.219785,1.0,1.0,0,Winner
2,Purdue,B10,33,29,126.2,94.7,0.9644,56.0,47.7,16.5,...,40.8,31.4,67.6,11.00,1.0,1.651423,2.0,1.0,1,Runner-Up
3,Iowa St.,B12,34,27,113.6,86.5,0.9583,51.9,47.1,15.7,...,34.9,31.5,67.6,6.90,2.0,1.966927,4.0,1.0,2,Final Four
4,Auburn,SEC,34,27,120.7,92.1,0.9573,54.1,43.4,14.9,...,35.2,29.8,69.8,5.50,4.0,4.541897,10.0,3.0,2,Final Four
0,Houston,B12,34,30,119.2,85.5,0.9785,49.7,44.0,13.7,...,34.7,30.0,63.3,10.60,1.0,1.754744,3.0,1.0,3,Elite Eight
7,Marquette,BE,34,25,118.9,94.6,0.9328,55.1,49.7,14.3,...,35.8,33.6,69.1,6.50,2.0,3.288688,6.0,2.0,3,Elite Eight
11,Illinois,B10,34,26,125.3,101.1,0.9221,53.8,48.0,15.1,...,34.9,34.3,69.9,6.00,3.0,3.945184,8.0,2.0,3,Elite Eight
39,Dayton,A10,31,24,117.4,100.7,0.8547,56.6,47.9,15.8,...,40.2,31.7,64.0,2.60,7.0,8.275740,27.0,7.0,3,Elite Eight
35,Ohio St.,B10,33,20,115.5,98.4,0.8636,51.2,48.2,15.6,...,34.3,34.7,65.4,-0.23,NaN,9.009435,31.0,8.0,4,Sweet Sixteen
46,South Carolina,SEC,33,26,114.4,98.9,0.8420,50.8,48.0,15.5,...,33.5,33.6,63.0,4.70,6.0,7.993735,26.0,7.0,4,Sweet Sixteen
28,San Diego St.,MWC,32,24,111.5,93.9,0.8789,49.8,47.2,16.0,...,31.3,30.5,66.1,2.60,5.0,7.298680,25.0,7.0,4,Sweet Sixteen
25,New Mexico,MWC,34,26,114.8,95.5,0.8927,51.0,48.0,13.9,...,33.4,30.6,72.8,1.70,11.0,9.050807,33.0,9.0,4,Sweet Sixteen
22,Michigan St.,B10,33,19,112.7,93.3,0.8983,51.5,48.0,14.7,...,35.9,32.8,65.3,0.21,9.0,9.551414,39.0,10.0,4,Sweet Sixteen
19,Texas,B12,32,20,119.0,98.3,0.9006,53.7,49.0,16.6,...,36.1,34.8,67.2,1.20,7.0,8.871719,30.0,8.0,4,Sweet Sixteen
20,St. John's,BE,33,20,119.1,98.3,0.9005,50.9,49.5,15.7,...,34.1,35.0,69.2,0.32,NaN,9.025539,32.0,8.0,4,Sweet Sixteen
27,Texas Tech,B12,33,23,117.5,98.4,0.8846,52.8,49.1,16.5,...,36.5,32.1,66.4,3.40,6.0,5.909659,16.0,4.0,4,Sweet Sixteen

In [246]:
''' 
now to the above we need to do the following:
    1. We need to get the seeds for the current data 
    2. We need to then run to see the final finishes 
'''

' \nnow to the above we need to do the following:\n    1. We need to get the seeds for the current data \n    2. We need to then run to see the final finishes \n'