In [2]:
import numpy as np 
import pandas as pd 
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

In [3]:
cbb = pd.read_csv('/Users/visheshgupta/Desktop/Final_Project_DE/archive/cbb.csv')

In [4]:
cbb.columns

Index(['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'POSTSEASON', 'SEED', 'YEAR'],
      dtype='object')

In [5]:
cbb24 = pd.read_csv('/Users/visheshgupta/Desktop/Final_Project_DE/archive/cbb24.csv')

In [6]:
cbb24.columns

Index(['RK', 'TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG%',
       'EFGD%', 'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D',
       '3P_O', '3P_D', 'ADJ_T', 'WAB', 'SEED'],
      dtype='object')

In [7]:
cbb24['EFG_O'] = cbb24['EFG%']
cbb24['EFG_D'] = cbb24['EFGD%']
cbb24 = cbb24[['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'SEED']]

In [8]:
cbb24

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,SEED
0,Houston,B12,34,30,119.2,85.5,0.9785,49.7,44.0,13.7,...,30.2,29.9,39.0,48.4,43.4,34.7,30.0,63.3,10.6,1.0
1,Connecticut,BE,34,31,127.1,93.6,0.9712,57.1,45.1,14.9,...,26.8,33.3,32.5,58.5,43.7,36.7,31.9,64.6,11.3,1.0
2,Purdue,B10,33,29,126.2,94.7,0.9644,56.0,47.7,16.5,...,24.7,42.8,23.0,53.2,48.1,40.8,31.4,67.6,11.0,1.0
3,Iowa St.,B12,34,27,113.6,86.5,0.9583,51.9,47.1,15.7,...,29.4,36.1,35.2,51.7,46.9,34.9,31.5,67.6,6.9,2.0
4,Auburn,SEC,34,27,120.7,92.1,0.9573,54.1,43.4,14.9,...,30.3,38.2,41.0,54.9,42.8,35.2,29.8,69.8,5.5,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,Stonehill,NEC,30,4,90.3,114.2,0.0629,46.7,52.7,19.5,...,31.0,22.6,29.4,47.9,51.7,30.1,35.9,68.1,-22.0,NaN
358,St. Francis PA,NEC,28,8,93.1,118.1,0.0608,47.2,53.0,21.2,...,31.3,32.6,35.4,45.7,52.9,33.2,35.4,65.4,-18.6,NaN
359,IUPUI,Horz,29,6,92.1,116.9,0.0607,46.5,58.2,21.3,...,35.5,33.2,33.4,49.5,59.0,24.7,38.0,67.3,-21.6,NaN
360,Coppin St.,MEAC,29,2,85.1,111.1,0.0445,42.1,51.3,22.9,...,38.6,31.1,38.3,41.9,51.0,28.3,34.5,66.3,-22.9,NaN
361,Mississippi Valley St.,SWAC,31,1,85.4,116.2,0.0283,42.5,55.6,24.0,...,35.7,33.0,41.6,41.9,55.6,29.2,37.0,64.5,-22.7,NaN

In [9]:
cbb

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,...,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,...,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,...,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,...,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,...,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3518,Toledo,MAC,34,27,119.9,109.6,0.7369,56.3,52.9,13.6,...,27.5,54.6,52.1,39.7,36.1,69.5,-1.2,NaN,NaN,2023
3519,Liberty,ASun,33,27,111.4,97.3,0.8246,55.5,49.3,16.0,...,27.8,56.4,48.6,36.4,33.6,64.4,-2.0,NaN,NaN,2023
3520,Utah Valley,WAC,34,28,107.1,94.6,0.8065,51.7,44.0,19.3,...,28.7,52.5,42.8,33.4,31.1,69.8,-0.3,NaN,NaN,2023
3521,UAB,CUSA,38,29,112.4,97.0,0.8453,50.3,47.3,17.3,...,28.9,48.8,47.2,35.6,31.6,70.7,-0.5,NaN,NaN,2023
3522,North Texas,CUSA,36,31,110.0,93.8,0.8622,51.2,44.5,19.8,...,40.2,49.6,44.2,35.7,30.1,58.7,1.1,NaN,NaN,2023

In [10]:
cbb.to_csv('train_data.csv', index=False)

In [11]:
cbb24.to_csv('test_data.csv', index=False)

In [12]:
#dummy data:

In [13]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.barttorvik.com/"
response = requests.get(url)

# Parse the HTML
soup = BeautifulSoup(response.text, "html.parser")

# Inspect the page structure and find the table or relevant data
# Example: Extracting table data
table = soup.find("table")
rows = table.find_all("tr")

data = []
for row in rows:
    cols = row.find_all("td")
    cols = [ele.text.strip() for ele in cols]
    data.append(cols)

# Convert to DataFrame and save as CSV
df = pd.DataFrame(data)
df = df.dropna(how="all").reset_index(drop=True)

df.columns = ['RK', 'TEAM', 'CONF', 'G', 'REC', 'ADJOE', 'ADJDE', 'BARTHAG', "EFG_O", "EFG_D", 'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', "2P_O", "2P_D", "3P_O", "3P_D", '3PR', '3PRD', 'ADJ_T', 'WAB']
df = df[[
    "TEAM", "CONF", "G", "ADJOE", "ADJDE", "BARTHAG", 
    "EFG_O", "EFG_D", "TOR", "TORD", "ORB", "DRB", "FTR", "FTRD", 
    "2P_O", "2P_D", "3P_O", "3P_D", "ADJ_T", "WAB"
]]
df.to_csv("current_cbb_live_data.csv", index=False)

In [14]:
df.columns

Index(['TEAM', 'CONF', 'G', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB'],
      dtype='object')

In [15]:

cbb.columns

Index(['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'POSTSEASON', 'SEED', 'YEAR'],
      dtype='object')

In [16]:
cbb24.columns

Index(['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'SEED'],
      dtype='object')

In [17]:
len(cbb.columns)

24

In [18]:
len(cbb24.columns)

22

In [19]:
'''   
# columns that we are missing in our scrapped date:
1. W : no of  games a team won
2. POST SEASON: What position they finished. This is what we are predciting so we are good
3. Seed: We cannot know this information 
4. Year: This is Trivial 
'''

'   \n# columns that we are missing in our scrapped date:\n1. W : no of  games a team won\n2. POST SEASON: What position they finished. This is what we are predciting so we are good\n3. Seed: We cannot know this information \n4. Year: This is Trivial \n'

In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from pygam import LinearGAM, s, f

# Filter rows with non-null SEED values and convert SEED to integers
cbb_model = cbb[cbb['SEED'].notnull()]
cbb_model['SEED'] = cbb_model['SEED'].astype(int)

# Define feature columns and the target variable
features = [
    'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D', 'TOR', 'TORD', 'ORB',
    'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O', '3P_D', 'ADJ_T', 'WAB'
]
X = cbb_model[features]
y = cbb_model['SEED']

# Extract the features from cbb24 for prediction
cbb24_seedless = cbb24[features]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
cbb24_scaled = scaler.transform(cbb24_seedless)

# Fit a GAM model
gam = LinearGAM(s(0) + s(1) + s(2) + s(3) + s(4) + s(5) + s(6) + 
                s(7) + s(8) + s(9) + s(10) + s(11) + s(12) + 
                s(13) + s(14) + s(15) + s(16)).fit(X_train, y_train)

# Predict on the test set and compute MAE
y_pred = gam.predict(X_test)
y_pred_rounded = np.round(y_pred).clip(1, 16)  # Clip predictions to valid seed range
mae = mean_absolute_error(y_test, y_pred_rounded)
print(f"Mean Absolute Error (MAE): {mae}")

# Predict seeds for cbb24
cbb24_predictions = gam.predict(cbb24_scaled)
cbb24['predicted_seed_score'] = cbb24_predictions  # Store raw predictions for ranking

# Rank teams based on predicted seed scores
cbb24['rank'] = cbb24['predicted_seed_score'].rank(method='min', ascending=True)

# Assign seeds to top 68 teams
cbb24['predicted_seed'] = np.nan  # Initialize with NaN
top_68 = cbb24.nsmallest(68, 'predicted_seed_score')  # Select top 68 teams

# Create seed values for 68 teams
seed_values = []
for seed in range(1, 17):
    if seed == 11 or seed == 16:
        seed_values.extend([seed] * 6)  # 6 teams for seeds 11 and 16
    else:
        seed_values.extend([seed] * 4)  # 4 teams for other seeds

# Assign seeds to the top 68 teams
top_68['predicted_seed'] = seed_values

# Update the main DataFrame with the seeded teams
cbb24.update(top_68) 
cbb24 = cbb24.sort_values(by='predicted_seed')

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_72364/3855713373.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb_model['SEED'] = cbb_model['SEED'].astype(int)

Mean Absolute Error (MAE): 1.1323529411764706

In [21]:
cbb24

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,SEED,predicted_seed_score,rank,predicted_seed
0,Houston,B12,34,30,119.2,85.5,0.9785,49.7,44.0,13.7,...,48.4,43.4,34.7,30.0,63.3,10.6,1.0,-0.048552,1.0,1.0
1,Connecticut,BE,34,31,127.1,93.6,0.9712,57.1,45.1,14.9,...,58.5,43.7,36.7,31.9,64.6,11.3,1.0,2.043619,2.0,1.0
3,Iowa St.,B12,34,27,113.6,86.5,0.9583,51.9,47.1,15.7,...,51.7,46.9,34.9,31.5,67.6,6.9,2.0,3.124384,4.0,1.0
7,Marquette,BE,34,25,118.9,94.6,0.9328,55.1,49.7,14.3,...,56.0,49.2,35.8,33.6,69.1,6.5,2.0,2.579642,3.0,1.0
2,Purdue,B10,33,29,126.2,94.7,0.9644,56.0,47.7,16.5,...,53.2,48.1,40.8,31.4,67.6,11.0,1.0,3.132346,5.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,VMI,SC,29,4,87.8,110.7,0.0651,46.0,54.4,21.2,...,46.7,54.5,29.7,36.2,74.7,-22.6,NaN,12.308127,72.0,NaN
357,Stonehill,NEC,30,4,90.3,114.2,0.0629,46.7,52.7,19.5,...,47.9,51.7,30.1,35.9,68.1,-22.0,NaN,13.976493,117.0,NaN
358,St. Francis PA,NEC,28,8,93.1,118.1,0.0608,47.2,53.0,21.2,...,45.7,52.9,33.2,35.4,65.4,-18.6,NaN,17.229247,315.0,NaN
360,Coppin St.,MEAC,29,2,85.1,111.1,0.0445,42.1,51.3,22.9,...,41.9,51.0,28.3,34.5,66.3,-22.9,NaN,14.772240,147.0,NaN
361,Mississippi Valley St.,SWAC,31,1,85.4,116.2,0.0283,42.5,55.6,24.0,...,41.9,55.6,29.2,37.0,64.5,-22.7,NaN,16.350732,255.0,NaN

In [22]:
# import pandas as pd
# import numpy as np
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from sklearn.metrics import mean_absolute_error
# from sklearn.linear_model import LinearRegression
# from sklearn.ensemble import RandomForestRegressor
# from xgboost import XGBRegressor

# cbb_model = cbb[cbb['SEED'].notnull()]

# cbb_model['SEED'] = cbb_model['SEED'].astype(int)

# features = [
#     'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D', 'TOR', 'TORD', 'ORB',
#     'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O', '3P_D', 'ADJ_T', 'WAB'
# ]
# X = cbb_model[features]
# y = cbb_model['SEED']

# cbb24_seedless = cbb24[features]  

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# scaler = StandardScaler()
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)
# cbb24_scaled = scaler.transform(cbb24_seedless)

# models = {
#     'Linear Regression': LinearRegression(),
#     'Random Forest': RandomForestRegressor(random_state=42, n_estimators=100),
#     'XGBoost': XGBRegressor(random_state=42)
# }

# results = {}
# for model_name, model in models.items():
#     model.fit(X_train, y_train)
#     y_pred = model.predict(X_test)
#     y_pred_rounded = np.round(y_pred).clip(1, 16)  # Clip predictions to valid seed range
#     mae = mean_absolute_error(y_test, y_pred_rounded)
#     results[model_name] = mae

# # Predict seeds for cbb24 using the best-performing model
# best_model_name = max(results, key=results.get)
# best_model = models[best_model_name]
# cbb24_predictions = best_model.predict(cbb24_scaled)
# cbb24['predicted_seed_score'] = cbb24_predictions  # Store raw predictions for ranking

# # Rank teams based on predicted seed scores
# cbb24['rank'] = cbb24['predicted_seed_score'].rank(method='min', ascending=True)

# # Assign seeds to top 68 teams
# cbb24['predicted_seed'] = np.nan  # Initialize with NaN
# top_68 = cbb24.nsmallest(68, 'predicted_seed_score')  # Select top 68 teams

# # Create seed values for 68 teams
# seed_values = []
# for seed in range(1, 17):
#     if seed == 11 or seed == 16:
#         seed_values.extend([seed] * 6)  # 6 teams for seeds 11 and 16
#     else:
#         seed_values.extend([seed] * 4)  # 4 teams for other seeds

# # Assign seeds to the top 68 teams
# top_68['predicted_seed'] = seed_values

# # Update the main DataFrame with the seeded teams
# cbb24.update(top_68) 
# cbb24 = cbb24.sort_values(by='predicted_seed')

In [23]:
#results

In [24]:
cbb['POSTSEASON'].unique()

array(['2ND', 'Champions', 'E8', 'F4', nan, 'R32', 'R64', 'R68', 'S16'],
      dtype=object)

In [25]:
cbb

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,...,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,...,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,...,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,...,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,...,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3518,Toledo,MAC,34,27,119.9,109.6,0.7369,56.3,52.9,13.6,...,27.5,54.6,52.1,39.7,36.1,69.5,-1.2,NaN,NaN,2023
3519,Liberty,ASun,33,27,111.4,97.3,0.8246,55.5,49.3,16.0,...,27.8,56.4,48.6,36.4,33.6,64.4,-2.0,NaN,NaN,2023
3520,Utah Valley,WAC,34,28,107.1,94.6,0.8065,51.7,44.0,19.3,...,28.7,52.5,42.8,33.4,31.1,69.8,-0.3,NaN,NaN,2023
3521,UAB,CUSA,38,29,112.4,97.0,0.8453,50.3,47.3,17.3,...,28.9,48.8,47.2,35.6,31.6,70.7,-0.5,NaN,NaN,2023
3522,North Texas,CUSA,36,31,110.0,93.8,0.8622,51.2,44.5,19.8,...,40.2,49.6,44.2,35.7,30.1,58.7,1.1,NaN,NaN,2023

In [26]:
cbb

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,...,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,...,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,...,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,...,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,...,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3518,Toledo,MAC,34,27,119.9,109.6,0.7369,56.3,52.9,13.6,...,27.5,54.6,52.1,39.7,36.1,69.5,-1.2,NaN,NaN,2023
3519,Liberty,ASun,33,27,111.4,97.3,0.8246,55.5,49.3,16.0,...,27.8,56.4,48.6,36.4,33.6,64.4,-2.0,NaN,NaN,2023
3520,Utah Valley,WAC,34,28,107.1,94.6,0.8065,51.7,44.0,19.3,...,28.7,52.5,42.8,33.4,31.1,69.8,-0.3,NaN,NaN,2023
3521,UAB,CUSA,38,29,112.4,97.0,0.8453,50.3,47.3,17.3,...,28.9,48.8,47.2,35.6,31.6,70.7,-0.5,NaN,NaN,2023
3522,North Texas,CUSA,36,31,110.0,93.8,0.8622,51.2,44.5,19.8,...,40.2,49.6,44.2,35.7,30.1,58.7,1.1,NaN,NaN,2023

In [27]:
# import numpy as np
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# from sklearn.metrics import classification_report
# from pygam import LogisticGAM, s

# # Preprocessing POSTSEASON column
# cbb = cbb[cbb['POSTSEASON'].notnull()]  # Filter rows with POSTSEASON values
# label_encoder = LabelEncoder()
# cbb['POSTSEASON_LABEL'] = label_encoder.fit_transform(cbb['POSTSEASON'])  # Encode POSTSEASON

# # Select features for modeling
# postseason_features = [
#     'predicted_seed', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D', 'TOR',
#     'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O', '3P_D',
#     'ADJ_T', 'WAB'
# ]

# # Replace SEED with predicted_seed for cbb
# cbb['predicted_seed'] = cbb['SEED']  # Use actual SEED for training

# # Define X and y for training
# X_postseason = cbb[postseason_features]
# y_postseason = cbb['POSTSEASON_LABEL']

# # Train-test split
# X_train, X_test, y_train, y_test = train_test_split(
#     X_postseason, y_postseason, test_size=0.2, random_state=42
# )

# # One-hot encode the target variable for OvR
# encoder = OneHotEncoder(sparse_output=False)
# y_train_onehot = encoder.fit_transform(y_train.values.reshape(-1, 1))
# y_test_onehot = encoder.transform(y_test.values.reshape(-1, 1))

# # Train one LogisticGAM per class
# gam_models = []
# for class_idx in range(y_train_onehot.shape[1]):
#     gam = LogisticGAM(
#         s(0) + s(1) + s(2) + s(3) + s(4) + s(5) + s(6) +
#         s(7) + s(8) + s(9) + s(10) + s(11) + s(12) +
#         s(13) + s(14) + s(15) + s(16)
#     ).fit(X_train, y_train_onehot[:, class_idx])
#     gam_models.append(gam)

# # Predict probabilities for each class on test data
# probabilities = np.column_stack([gam.predict_proba(X_test) for gam in gam_models])

# # Assign the class with the highest probability
# y_pred = np.argmax(probabilities, axis=1)

# # Evaluate the model
# print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

# # Apply the model to cbb24 data
# cbb24_seeded = cbb24.dropna(subset=['predicted_seed'])

# X_cbb24 = cbb24_seeded[postseason_features]
# postseason_probs = np.column_stack([gam.predict_proba(X_cbb24) for gam in gam_models])

# # Define the number of teams per label
# label_counts = {
#     'Champion': 1,
#     'Runner-Up': 1,
#     'Final Four': 2,
#     'Elite Eight': 4,
#     'Sweet Sixteen': 8,
#     'Round of 32': 16,
#     'Round of 64': 32
# }

# # Assign labels systematically
# num_labels = len(label_counts)
# assigned_labels = np.full(len(cbb24_seeded), num_labels - 1)  # Default to lowest label
# remaining_teams = list(range(len(cbb24_seeded)))

# # Loop through each label, starting with the highest rank (Champion)
# for label_idx, (label, count) in enumerate(label_counts.items()):
#     if len(remaining_teams) == 0:
#         break
#     label_probs = postseason_probs[remaining_teams, label_idx]
#     top_indices = np.argsort(label_probs)[-count:]  # Get indices of top `count` teams
#     top_team_indices = [remaining_teams[i] for i in top_indices]  # Map back to original indices
#     for i in top_team_indices:
#         assigned_labels[i] = label_idx
#     remaining_teams = [team for team in remaining_teams if team not in top_team_indices]  # Exclude assigned teams

# # Map assigned labels back to POSTSEASON names
# cbb24_seeded['predicted_postseason_label'] = assigned_labels

# postseason_mapping = {
#     0: 'Winner',
#     1: 'Runner-Up',
#     2: 'Final Four',
#     3: 'Elite Eight',
#     4: 'Sweet Sixteen',
#     5: 'Round of 32',
#     6: 'Round of 64'
# }

# # Map the numerical labels to their descriptions
# cbb24_seeded['predicted_postseason_description'] = cbb24_seeded['predicted_postseason_label'].map(postseason_mapping)

# # Display the predictions
# cbb24_seeded

In [28]:
# Preprocess the POSTSEASON column in cbb
cbb = cbb[cbb['POSTSEASON'].notnull()]  # Filter rows with POSTSEASON values
label_encoder = LabelEncoder()
cbb['POSTSEASON_LABEL'] = label_encoder.fit_transform(cbb['POSTSEASON'])  # Encode POSTSEASON

# Select features for modeling
postseason_features = [
    'predicted_seed', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D', 'TOR',
    'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O', '3P_D',
    'ADJ_T', 'WAB'
]

# Replace SEED with predicted_seed for cbb
cbb['predicted_seed'] = cbb['SEED']  # Use actual SEED for training

# Define X and y for training
X_postseason = cbb[postseason_features]
y_postseason = cbb['POSTSEASON_LABEL']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_postseason, y_postseason, test_size=0.2, random_state=42
)

# Train a Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=42, n_estimators=100)
rf_classifier.fit(X_train, y_train)

# Evaluate on test data
y_pred = rf_classifier.predict(X_test)
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

# Apply the model to cbb24 data
cbb24_seeded = cbb24.dropna(subset=['predicted_seed'])

X_cbb24 = cbb24_seeded[postseason_features]
postseason_probs = rf_classifier.predict_proba(X_cbb24)

# Define the number of teams per label
label_counts = {
    'Champion': 1,
    'Runner-Up': 1,
    'Final Four': 2,
    'Elite Eight': 4,
    'Sweet Sixteen': 8,
    'Round of 32': 16,
    'Round of 64': 32
}

# Assign labels systematically
num_labels = len(label_counts)
assigned_labels = np.full(len(cbb24_seeded), num_labels - 1)  # Default to lowest label
remaining_teams = list(range(len(cbb24_seeded)))

# Loop through each label, starting with the highest rank (Champion)
for label_idx, (label, count) in enumerate(label_counts.items()):
    # Select top teams based on probabilities for the current label
    if len(remaining_teams) == 0:
        break
    label_probs = postseason_probs[remaining_teams, label_idx]
    top_indices = np.argsort(label_probs)[-count:]  # Get indices of top `count` teams
    top_team_indices = [remaining_teams[i] for i in top_indices]  # Map back to original indices
    for i in top_team_indices:
        assigned_labels[i] = label_idx
    remaining_teams = [team for team in remaining_teams if team not in top_team_indices]  # Exclude assigned teams

# Map assigned labels back to POSTSEASON names
cbb24_seeded['predicted_postseason_label'] = assigned_labels

              precision    recall  f1-score   support

         2ND       0.00      0.00      0.00         2
   Champions       0.00      0.00      0.00         1
          E8       0.00      0.00      0.00         8
          F4       0.00      0.00      0.00         7
         R32       0.52      0.28      0.36        40
         R64       0.65      0.77      0.70        66
         R68       0.00      0.00      0.00         5
         S16       0.15      0.71      0.25         7

    accuracy                           0.49       136
   macro avg       0.17      0.22      0.16       136
weighted avg       0.48      0.49      0.46       136

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_72364/4232653574.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb['POSTSEASON_LABEL'] = label_encoder.fit_transform(cbb['POSTSEASON'])  # Encode POSTSEASON
/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_72364/4232653574.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb['predicted_seed'] = cbb['SEED']  # Use actual SEED for training
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_72364/4232653574.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb24_seeded['predicted_postseason_label'] = assigned_labels

In [29]:
postseason_mapping = {
    0: 'Winner',
    1: 'Runner-Up',
    2: 'Final Four',
    3: 'Elite Eight',
    4: 'Sweet Sixteen',
    5: 'Round of 32',
    6: 'Round of 64'
}

# Map the numerical labels to their descriptions
cbb24_seeded['predicted_postseason_description'] = cbb24_seeded['predicted_postseason_label'].map(postseason_mapping)

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_72364/3013661406.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb24_seeded['predicted_postseason_description'] = cbb24_seeded['predicted_postseason_label'].map(postseason_mapping)

In [30]:
cbb24_seeded.sort_values('predicted_postseason_label').head(16)

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,3P_O,3P_D,ADJ_T,WAB,SEED,predicted_seed_score,rank,predicted_seed,predicted_postseason_label,predicted_postseason_description
1,Connecticut,BE,34,31,127.1,93.6,0.9712,57.1,45.1,14.9,...,36.7,31.9,64.6,11.30,1.0,2.043619,2.0,1.0,0,Winner
2,Purdue,B10,33,29,126.2,94.7,0.9644,56.0,47.7,16.5,...,40.8,31.4,67.6,11.00,1.0,3.132346,5.0,2.0,1,Runner-Up
3,Iowa St.,B12,34,27,113.6,86.5,0.9583,51.9,47.1,15.7,...,34.9,31.5,67.6,6.90,2.0,3.124384,4.0,1.0,2,Final Four
4,Auburn,SEC,34,27,120.7,92.1,0.9573,54.1,43.4,14.9,...,35.2,29.8,69.8,5.50,4.0,3.397901,6.0,2.0,2,Final Four
0,Houston,B12,34,30,119.2,85.5,0.9785,49.7,44.0,13.7,...,34.7,30.0,63.3,10.60,1.0,-0.048552,1.0,1.0,3,Elite Eight
7,Marquette,BE,34,25,118.9,94.6,0.9328,55.1,49.7,14.3,...,35.8,33.6,69.1,6.50,2.0,2.579642,3.0,1.0,3,Elite Eight
39,Dayton,A10,31,24,117.4,100.7,0.8547,56.6,47.9,15.8,...,40.2,31.7,64.0,2.60,7.0,9.193057,34.0,9.0,3,Elite Eight
12,Saint Mary's,WCC,32,26,115.8,93.7,0.9198,53.1,45.1,16.0,...,35.5,32.4,62.1,1.40,5.0,8.870090,31.0,8.0,3,Elite Eight
22,Michigan St.,B10,33,19,112.7,93.3,0.8983,51.5,48.0,14.7,...,35.9,32.8,65.3,0.21,9.0,9.681244,39.0,10.0,4,Sweet Sixteen
38,Washington St.,P12,33,24,112.8,96.6,0.8556,52.1,47.3,16.1,...,34.0,32.0,64.9,1.90,7.0,8.560500,28.0,7.0,4,Sweet Sixteen
20,St. John's,BE,33,20,119.1,98.3,0.9005,50.9,49.5,15.7,...,34.1,35.0,69.2,0.32,NaN,8.264338,27.0,7.0,4,Sweet Sixteen
28,San Diego St.,MWC,32,24,111.5,93.9,0.8789,49.8,47.2,16.0,...,31.3,30.5,66.1,2.60,5.0,7.612829,23.0,6.0,4,Sweet Sixteen
19,Texas,B12,32,20,119.0,98.3,0.9006,53.7,49.0,16.6,...,36.1,34.8,67.2,1.20,7.0,7.653224,24.0,6.0,4,Sweet Sixteen
25,New Mexico,MWC,34,26,114.8,95.5,0.8927,51.0,48.0,13.9,...,33.4,30.6,72.8,1.70,11.0,9.013796,33.0,9.0,4,Sweet Sixteen
27,Texas Tech,B12,33,23,117.5,98.4,0.8846,52.8,49.1,16.5,...,36.5,32.1,66.4,3.40,6.0,6.078926,16.0,4.0,4,Sweet Sixteen
46,South Carolina,SEC,33,26,114.4,98.9,0.8420,50.8,48.0,15.5,...,33.5,33.6,63.0,4.70,6.0,4.548346,10.0,3.0,4,Sweet Sixteen

In [31]:
''' 
now to the above we need to do the following:
    1. We need to get the seeds for the current data 
    2. We need to then run to see the final finishes 
'''

' \nnow to the above we need to do the following:\n    1. We need to get the seeds for the current data \n    2. We need to then run to see the final finishes \n'

In [32]:
cbb25 = pd.read_csv('/Users/visheshgupta/Desktop/Final_Project_DE/current_cbb_live_data.csv')

In [33]:
cbb25_seedless = cbb25[features]  
cbb25_scaled = scaler.transform(cbb25_seedless)
cbb25_predictions = gam.predict(cbb25_scaled)
cbb25['predicted_seed_score'] = cbb25_predictions  # Store raw predictions for ranking

# Rank teams based on predicted seed scores
cbb25['rank'] = cbb25['predicted_seed_score'].rank(method='min', ascending=True)

# Assign seeds to top 68 teams
cbb25['predicted_seed'] = np.nan  # Initialize with NaN
top_68_25 = cbb25.nsmallest(68, 'predicted_seed_score')  # Select top 68 teams

# Create seed values for 68 teams
seed_values = []
for seed in range(1, 17):
    if seed == 11 or seed == 16:
        seed_values.extend([seed] * 6)  # 6 teams for seeds 11 and 16
    else:
        seed_values.extend([seed] * 4)  # 4 teams for other seeds

# Assign seeds to the top 68 teams
top_68_25['predicted_seed'] = seed_values

# Update the main DataFrame with the seeded teams
cbb25.update(top_68_25) 
cbb25 = cbb25.sort_values(by='predicted_seed')

In [34]:
cbb25.dropna(subset = 'predicted_seed').head(20)

,TEAM,CONF,G,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,predicted_seed_score,rank,predicted_seed
310,Tarleton St. (A) 26 Michigan,WAC,5,95.6338,106.8231,0.216931,42.9325,59.1349,32.1364,20.8710,...,52.3344,39.0348,56.2285,35.2115,41.9352,69.5181,-2.02900,-0.066409,3.0,1.0
360,Arkansas Pine Bluff,SWAC,6,94.1353,115.6364,0.085836,49.6198,60.7359,23.6345,13.0337,...,33.2171,52.8146,67.2364,29.5259,35.6262,72.5300,-2.73340,-5.940655,1.0,1.0
249,North Carolina Central,MEAC,6,102.0214,109.0287,0.319525,48.4222,56.5321,18.4204,23.4280,...,49.2336,48.6231,65.6360,32.1198,25.9270,68.1275,-3.53560,-0.819295,2.0,1.0
322,Le Moyne,NEC,5,98.8282,111.7344,0.195232,45.3282,56.7323,19.9264,15.6262,...,39.7262,44.6296,60.9341,30.6236,33.3187,69.1200,-2.33160,0.794385,4.0,1.0
260,Lehigh,Pat,5,100.1257,107.8254,0.298226,47.5241,56.0308,17.1145,13.4326,...,33.9182,47.7248,59.5330,31.4215,32.5166,70.3120,-2.02910,1.211908,5.0,2.0
138,UMass Lowell,AE,5,105.3148,103.2142,0.556914,45.3282,50.2185,20.6284,16.2238,...,35.3204,50.0198,49.7160,22.9351,34.4223,71.9410,-0.51400,1.302490,6.0,2.0
313,Tennessee Tech,OVC,6,97.9302,109.7304,0.213731,52.4130,49.7168,17.8169,19.5114,...,23.4360,52.9143,51.9192,34.6134,30.6123,68.0279,-1.62500,2.363274,8.0,2.0
22,Ohio St.,B10,4,114.2340,95.5250,0.886723,54.8800,34.0100,18.2193,16.0244,...,40.2274,52.3160,35.0200,38.6500,21.6400,68.7228,0.52600,1.984812,7.0,2.0
163,UNC Wilmington,CAA,4,104.9155,105.5192,0.483216,46.7255,56.2312,15.1740,15.5265,...,36.0211,51.9165,62.5351,25.4328,31.1136,68.4252,-0.00730,4.410944,11.0,3.0
128,Akron,MAC,3,104.7159,101.8119,0.580913,44.1307,53.1243,15.9960,17.3192,...,16.8300,35.4362,58.5318,37.1730,28.6770,68.4251,-0.91820,4.653327,12.0,3.0
336,Alabama A&M,SWAC,5,94.0354,108.2264,0.165834,36.5362,57.1332,24.9353,23.5270,...,65.2362,37.8353,58.9325,22.5353,35.9275,71.6560,-1.22160,3.208751,9.0,3.0
16,Creighton,BE,4,115.9140,95.6270,0.901517,59.6150,39.7900,18.1183,13.7320,...,10.7100,70.3200,37.4500,31.5211,28.3690,69.2194,0.20510,3.823266,10.0,3.0
114,Sam Houston St. (H) 0 Trinity (TX) (won),CUSA,5,108.6960,103.4145,0.637412,56.4480,55.7299,19.6255,22.1490,...,35.2202,49.3217,54.5241,44.0900,38.6320,70.5105,-0.32107,5.237964,15.0,4.0
362,Mississippi Valley St.,SWAC,5,89.0363,112.8355,0.061636,36.7361,56.2312,28.6363,12.5347,...,54.5351,38.4351,61.8346,21.2362,31.5145,68.3258,-1.22100,4.901021,14.0,4.0
352,West Georgia,ASun,5,93.8355,110.7330,0.129435,43.8310,59.6351,20.0268,15.7260,...,32.2154,43.4309,66.0361,29.8253,34.6234,70.1134,-3.23510,5.367941,16.0,4.0
231,Norfolk St.,MEAC,6,102.8203,108.1260,0.358723,52.9117,45.4700,18.4204,18.1168,...,32.5159,55.2960,47.5104,31.7207,29.4980,67.1319,-1.12010,4.840868,13.0,4.0
43,Iowa,B10,5,114.7280,99.4770,0.838144,57.3400,48.7140,15.3800,23.1350,...,19.0900,56.6730,56.1278,38.8450,24.4160,72.8220,0.62300,5.417516,17.0,5.0
327,Delaware St.,MEAC,5,94.7347,107.8252,0.183433,38.5355,55.3287,18.9225,20.4830,...,38.0244,40.0337,59.3328,20.0363,34.4223,70.0138,-1.82750,5.791706,19.0,5.0
307,Stony Brook,CAA,5,98.7283,110.0313,0.224031,44.6300,60.2357,19.4250,13.3331,...,29.5104,42.4320,65.1359,32.2195,35.3252,69.3188,-1.42360,5.442182,18.0,5.0
1,Duke,ACC,4,118.5600,89.9300,0.960020,56.9460,39.0500,13.4330,20.1930,...,22.4270,58.0610,39.3120,37.2710,25.7250,69.8153,-0.15870,5.944291,20.0,5.0

In [35]:
# Preprocess the POSTSEASON column in cbb
cbb = cbb[cbb['POSTSEASON'].notnull()]  # Filter rows with POSTSEASON values
label_encoder = LabelEncoder()
cbb['POSTSEASON_LABEL'] = label_encoder.fit_transform(cbb['POSTSEASON'])  # Encode POSTSEASON

# Select features for modeling
postseason_features = [
    'predicted_seed', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D', 'TOR',
    'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O', '3P_D',
    'ADJ_T', 'WAB'
]

# Replace SEED with predicted_seed for cbb
cbb['predicted_seed'] = cbb['SEED']  # Use actual SEED for training

# Define X and y for training
X_postseason = cbb[postseason_features]
y_postseason = cbb['POSTSEASON_LABEL']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_postseason, y_postseason, test_size=0.2, random_state=42
)

# Train a Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=42, n_estimators=100)
rf_classifier.fit(X_train, y_train)

# Evaluate on test data
y_pred = rf_classifier.predict(X_test)
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

# Apply the model to cbb24 data
cbb25_seeded = cbb25.dropna(subset=['predicted_seed'])

X_cbb25 = cbb25_seeded[postseason_features]
postseason_probs_25 = rf_classifier.predict_proba(X_cbb25)

# Define the number of teams per label
label_counts = {
    'Champion': 1,
    'Runner-Up': 1,
    'Final Four': 2,
    'Elite Eight': 4,
    'Sweet Sixteen': 8,
    'Round of 32': 16,
    'Round of 64': 32
}

# Assign labels systematically
num_labels_25 = len(label_counts)
assigned_labels_25 = np.full(len(cbb25_seeded), num_labels_25 - 1)  # Default to lowest label
remaining_teams_25 = list(range(len(cbb25_seeded)))

# Loop through each label, starting with the highest rank (Champion)
for label_idx, (label, count) in enumerate(label_counts.items()):
    # Select top teams based on probabilities for the current label
    if len(remaining_teams_25) == 0:
        break
    label_probs_25 = postseason_probs_25[remaining_teams_25, label_idx]
    top_indices_25 = np.argsort(label_probs_25)[-count:]  # Get indices of top `count` teams
    top_team_indices_25 = [remaining_teams_25[i] for i in top_indices_25]  # Map back to original indices
    for i in top_team_indices_25:
        assigned_labels_25[i] = label_idx
    remaining_teams_25 = [team for team in remaining_teams_25 if team not in top_team_indices_25]  # Exclude assigned teams

# Map assigned labels back to POSTSEASON names
cbb25_seeded['predicted_postseason_label'] = assigned_labels_25

              precision    recall  f1-score   support

         2ND       0.00      0.00      0.00         2
   Champions       0.00      0.00      0.00         1
          E8       0.00      0.00      0.00         8
          F4       0.00      0.00      0.00         7
         R32       0.52      0.28      0.36        40
         R64       0.65      0.77      0.70        66
         R68       0.00      0.00      0.00         5
         S16       0.15      0.71      0.25         7

    accuracy                           0.49       136
   macro avg       0.17      0.22      0.16       136
weighted avg       0.48      0.49      0.46       136

/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_72364/3542001177.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb25_seeded['predicted_postseason_label'] = assigned_labels_25

In [36]:
postseason_mapping = {
    0: 'Winner',
    1: 'Runner-Up',
    2: 'Final Four',
    3: 'Elite Eight',
    4: 'Sweet Sixteen',
    5: 'Round of 32',
    6: 'Round of 64'
}

# Map the numerical labels to their descriptions
cbb25_seeded['predicted_postseason_description'] = cbb25_seeded['predicted_postseason_label'].map(postseason_mapping)

/var/folders/mc/2wjfdchj6vsffbrpfbfgqw4w0000gn/T/ipykernel_72364/863179138.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cbb25_seeded['predicted_postseason_description'] = cbb25_seeded['predicted_postseason_label'].map(postseason_mapping)

In [37]:
cbb25_seeded.sort_values('predicted_postseason_label').head(16)

,TEAM,CONF,G,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,...,2P_D,3P_O,3P_D,ADJ_T,WAB,predicted_seed_score,rank,predicted_seed,predicted_postseason_label,predicted_postseason_description
16,Creighton,BE,4,115.9140,95.6270,0.901517,59.6150,39.7900,18.1183,13.7320,...,37.4500,31.5211,28.3690,69.2194,0.20510,3.823266,10.0,3.0,0,Winner
1,Duke,ACC,4,118.5600,89.9300,0.960020,56.9460,39.0500,13.4330,20.1930,...,39.3120,37.2710,25.7250,69.8153,-0.15870,5.944291,20.0,5.0,1,Runner-Up
5,Iowa St.,B12,3,113.8370,89.9200,0.938060,54.6890,40.8180,13.3300,28.0100,...,43.0440,31.0225,25.4230,69.3191,0.10660,6.189503,24.0,6.0,2,Final Four
43,Iowa,B10,5,114.7280,99.4770,0.838144,57.3400,48.7140,15.3800,23.1350,...,56.1278,38.8450,24.4160,72.8220,0.62300,5.417516,17.0,5.0,2,Final Four
29,Rutgers,B10,4,113.0430,95.6260,0.872130,56.1510,45.3650,13.6390,14.3305,...,42.6370,36.8790,33.3187,69.4185,0.23470,7.877183,48.0,12.0,3,Elite Eight
128,Akron,MAC,3,104.7159,101.8119,0.580913,44.1307,53.1243,15.9960,17.3192,...,58.5318,37.1730,28.6770,68.4251,-0.91820,4.653327,12.0,3.0,3,Elite Eight
27,Indiana (H) 177 UNC Greensboro (won),B10,4,114.4300,96.5370,0.875528,57.2430,41.1200,18.6211,19.3123,...,41.5310,35.7990,27.1440,70.8910,0.46330,7.694813,41.0,11.0,3,Elite Eight
20,Cincinnati,B12,4,115.2210,95.7290,0.894421,64.6300,39.0500,13.1240,19.8105,...,38.9900,44.9700,26.2300,67.9284,0.33420,8.807703,62.0,15.0,3,Elite Eight
22,Ohio St.,B10,4,114.2340,95.5250,0.886723,54.8800,34.0100,18.2193,16.0244,...,35.0200,38.6500,21.6400,68.7228,0.52600,1.984812,7.0,2.0,4,Sweet Sixteen
12,Connecticut,BE,4,114.0360,93.4700,0.908613,61.3900,36.4200,17.7165,22.4450,...,34.4100,35.3112,27.3450,67.2317,0.09690,7.553009,40.0,10.0,4,Sweet Sixteen
32,Michigan St.,B10,5,111.7550,95.0190,0.865133,50.0184,45.7750,16.0100,19.8105,...,46.7910,22.1357,29.5990,68.9212,0.02720,7.702467,42.0,11.0,4,Sweet Sixteen
40,VCU vs. 85 Seton Hall (lost),A10,5,109.9760,94.8160,0.846341,51.9143,40.0120,19.9264,25.2900,...,39.0100,31.5211,28.4730,69.8154,-0.36111,8.995776,67.0,16.0,4,Sweet Sixteen
28,Pittsburgh,ACC,5,114.3310,96.5380,0.874229,59.0210,40.6150,12.7160,18.9138,...,40.4190,37.0740,27.3450,69.1199,0.52500,8.071307,51.0,13.0,4,Sweet Sixteen
18,Marquette,BE,5,113.7390,93.9110,0.899519,52.6123,47.6109,11.9800,24.7150,...,48.8130,30.7234,30.6123,70.6960,1.51000,8.610300,57.0,14.0,4,Sweet Sixteen
53,N.C. State,ACC,4,111.0610,98.1610,0.806554,55.1720,43.8450,15.8920,23.2320,...,49.3143,27.1306,22.2500,70.2127,0.14620,8.881326,64.0,16.0,4,Sweet Sixteen
62,LSU,SEC,4,109.5820,97.2480,0.798763,55.7580,39.6800,19.2239,16.0244,...,43.9590,31.2220,19.7100,70.1133,0.81500,7.341025,39.0,10.0,4,Sweet Sixteen

In [38]:
from datetime import datetime
current_date = datetime.now().strftime("%Y%m%d")
file_name = f"cbb25_seeded_{current_date}.csv"
cbb25_seeded.to_csv(file_name, index=False)